// Recetas de la casa. Cantidades para 4 porciones (la app las ajusta a las personas).
//
// ing: [cantidad, unidad, nombre, pasillo]  ó  ['Subtítulo']
//   unidad:  g | taza | cda | cdta | u (unidades) | gusto
//   nombre:  "singular|plural" cuando cambia con la cantidad
//   pasillo: car carnes/pollo/pescado · ver frutas y verduras · lac huevos y lácteos
//            gra arroz, granos y harinas · pan arepas, pan y tortillas · sal salsas y especias
//            otr enlatados y otros · bas básicos de la cocina · sob sobrado de otro día
// m: desayuno | almuerzo | comida | bebida | postre | salsa
// pica: cómo hacerla picante para el que le guste · salsas: ids de salsas que le quedan bien
// fv: cuál miniatura del video usar de foto (por defecto oardefault)
// a: aparatos que necesita. "freidora|horno" = sirve cualquiera de los dos.
// o: 'h4s' = inspirada en @hunt4shredz (video en inglés) · 'fb' = video de Facebook · 'juan' = idea de Juan
// fija: texto = receta de una sola tanda, no cambia con las personas
// ingles: el video está en inglés · de: quién hizo el video · reposo: tiempo de nevera (avenas trasnochadas, etc.) · foto: archivo en fotos/
// Video: v = id de YouTube · vu = link de otro sitio (Facebook…) · vq = búsqueda en YouTube
// liv = cómo servirla para bajar de peso · mus = cómo servirla para ganar músculo
// kcal / prot: aproximados por porción, sin acompañantes.

const RECETAS = [
  // ───────────── Inspiradas en @hunt4shredz ─────────────
  {
    id: 'tenders-miel-picante', o: 'h4s', v: '9GesJYk6gQY',
    n: 'Tenders de pollo con limón, pimienta y miel', e: '🍗',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['freidora|horno'], t: 30, d: 'Fácil', kcal: 430, prot: 45,
    ing: [
      [800, 'g', 'filetes de pechuga de pollo (o pechuga en tiras)', 'car'],
      [0.5, 'taza', 'harina de trigo', 'gra'],
      [2, 'u', 'huevo|huevos', 'lac'],
      [3, 'taza', 'Corn Flakes sin azúcar', 'gra'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [1, 'cdta', 'pimienta negra molida', 'bas'],
      [1, 'cdta', 'ajo en polvo', 'bas'],
      [1, 'cdta', 'sal', 'bas'],
      [null, 'gusto', 'aceite en spray', 'bas'],
      ['Salsa de miel y limón'],
      [3, 'cda', 'miel de abejas', 'sal'],
      [1, 'cdta', 'mantequilla (opcional)', 'lac'],
    ],
    pasos: [
      'Ralla la cáscara del limón (solo lo verde) y mézclala con la pimienta, el ajo en polvo y la sal. Úntale la mitad al pollo.',
      'Arma 3 platos: uno con la harina, otro con los huevos batidos y otro con los Corn Flakes triturados con la mano.',
      'Pasa cada tira de pollo por harina, luego por huevo y luego por Corn Flakes, apretando bien para que se pegue.',
      'Rocía con aceite en spray. Freidora de aire a 200 °C por 10 a 12 minutos, volteando a la mitad. En horno: 220 °C por 18 a 20 minutos.',
      'Salsa: calienta la miel con el jugo del limón (y la mantequilla si quieres) en una ollita a fuego bajo 1 minuto. Rocíala sobre los tenders y espolvorea el resto del condimento de limón.',
    ],
    liv: 'Sirve 4 o 5 tenders con una ensalada grande en vez de papas, y solo 1 cucharadita de la salsa de miel.',
    pica: 'Al que le guste picante: unas gotas de salsa picante en su miel.',
    salsas: ['salsa-yogur-ajo', 'salsa-miel-mostaza', 'salsa-ranch'],
    mus: 'Porción y media de pollo (6 o 7 tenders) con papa criolla o arroz, y la salsa de miel completa.',
    adel: 'Se pueden apanar el día anterior y guardar crudos en la nevera, o congelarlos ya apanados.',
    con: 'Ensalada fresca o papa criolla en la freidora.',
  },
  {
    id: 'burritos-cajun', o: 'h4s', v: 'cYrEJoqG8bA',
    n: 'Burritos de pollo cajún con arroz', e: '🌯',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['estufa'], t: 35, d: 'Fácil', kcal: 600, prot: 46,
    ing: [
      [700, 'g', 'muslos de pollo sin hueso ni piel (o pechuga)', 'car'],
      [1, 'u', 'cebolla cabezona|cebollas cabezonas', 'ver'],
      [1, 'u', 'pimentón rojo|pimentones rojos', 'ver'],
      [1, 'u', 'pimentón verde|pimentones verdes', 'ver'],
      [2, 'cda', 'condimento cajún suave (o pimentón dulce + ajo + orégano)', 'sal'],
      [1, 'taza', 'arroz blanco (crudo)', 'gra'],
      [8, 'u', 'tortilla de trigo integral|tortillas de trigo integrales', 'pan'],
      ['Salsa cajún cremosa'],
      [1, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'cdta', 'perejil seco', 'sal'],
      [1, 'cdta', 'ajo en polvo', 'bas'],
    ],
    pasos: [
      'Cocina el arroz como siempre.',
      'Corta el pollo en cubitos, y la cebolla y los pimentones en tiras.',
      'En una sartén grande con un chorrito de aceite, dora el pollo con casi todo el condimento cajún, 6 a 8 minutos. Agrega la cebolla y los pimentones y cocina 5 minutos más.',
      'Mezcla el arroz con el pollo en la sartén.',
      'Salsa: revuelve el yogur con el perejil, el ajo en polvo, una pizca de sal y el resto del condimento cajún.',
      'Rellena cada tortilla con la mezcla y un poco de salsa, enróllala y dórala en la sartén seca 1 minuto por cada lado para que cierre.',
    ],
    liv: 'Un burrito en vez de dos, con ensalada. O sirve el relleno en un plato sin tortilla.',
    pica: 'Al que le guste picante: una pizca de cayena o salsa picante en su burrito.',
    salsas: ['salsa-ranch', 'salsa-aguacate', 'guacamole-licuadora'],
    mus: 'Dos burritos completos y un vaso de leche o de yogur griego.',
    adel: 'El relleno dura 4 días en la nevera. Los burritos armados se congelan envueltos en papel aluminio.',
    con: 'Guacamole en licuadora.',
  },
  {
    id: 'pollo-3-marinadas', o: 'h4s', v: 'BxncjnpLT-I',
    n: 'Pollo con 3 marinadas (limón, mostaza-miel y soya-jengibre)', e: '🍋',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['horno|freidora'], t: 40, d: 'Fácil', kcal: 340, prot: 45,
    ing: [
      [900, 'g', 'pechuga de pollo sin hueso', 'car'],
      ['Marinada 1: limón y hierbas'],
      [2, 'cda', 'aceite de oliva', 'bas'],
      [2, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [1, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'romero y tomillo (frescos o secos)', 'sal'],
      [1, 'cdta', 'mostaza Dijon (o normal)', 'sal'],
      ['Marinada 2: mostaza y miel'],
      [1, 'cda', 'mostaza Dijon (o normal)', 'sal'],
      [1, 'cda', 'miel de abejas', 'sal'],
      [1, 'cda', 'vinagre de manzana', 'sal'],
      [1, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [0.5, 'cdta', 'pimentón en polvo (paprika)', 'sal'],
      ['Marinada 3: soya y jengibre'],
      [2, 'cda', 'salsa soya baja en sodio', 'sal'],
      [1, 'cda', 'miel de abejas', 'sal'],
      [1, 'cda', 'vinagre de manzana', 'sal'],
      [1, 'cdta', 'jengibre fresco rallado', 'ver'],
      [1, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'aceite de ajonjolí (opcional)', 'sal'],
    ],
    pasos: [
      'Divide el pollo en 3 bolsas con cierre (o 3 recipientes con tapa).',
      'Marinada 1: aceite, jugo de los limones, ajo picado, romero, tomillo, mostaza, sal y pimienta.',
      'Marinada 2: mostaza, miel, vinagre, ajo picado, pimentón y sal.',
      'Marinada 3: soya, miel, vinagre, jengibre, ajo picado y aceite de ajonjolí.',
      'Echa cada marinada en su bolsa, masajea y deja en la nevera mínimo 30 minutos (mejor toda la noche).',
      'Horno a 200 °C por 25 minutos, o freidora de aire a 190 °C por 15 a 18 minutos, volteando a la mitad. Corta el más grueso: no debe quedar rosado por dentro.',
    ],
    liv: 'Perfecta para bajar de peso: acompaña con verduras y media taza de arroz o una papa pequeña.',
    pica: 'Al que le guste picante: en una bolsita aparte, una pizca de cayena en la marinada 2 o un chorrito de sriracha en la 3.',
    salsas: ['salsa-yogur-ajo', 'vinagreta-limon'],
    mus: 'Una pechuga grande (unos 250 g) con una taza de arroz y aguacate.',
    adel: 'Ideal para el domingo: marina las 3 bolsas y congélalas. La noche anterior pasa una a la nevera.',
    con: 'Arroz, ensalada o verduras al vapor.',
  },
  {
    id: 'burritos-desayuno', o: 'h4s', v: 'ghwbWfca5gM',
    n: 'Burritos de desayuno con carne y huevo', e: '🌯',
    m: ['desayuno'], p: 'res', a: ['estufa', 'freidora|horno'], t: 35, d: 'Media', kcal: 600, prot: 40,
    ing: [
      [2, 'u', 'papa pastusa mediana|papas pastusas medianas', 'ver'],
      [0.5, 'u', 'cebolla cabezona|cebollas cabezonas', 'ver'],
      [450, 'g', 'carne molida de res magra', 'car'],
      [2, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'comino', 'bas'],
      [1, 'cdta', 'pimentón en polvo (paprika)', 'sal'],
      [1, 'cda', 'salsa inglesa', 'sal'],
      [6, 'u', 'huevo|huevos', 'lac'],
      [4, 'u', 'tortilla de trigo grande|tortillas de trigo grandes', 'pan'],
      [1, 'u', 'tallo de cebolla larga|tallos de cebolla larga', 'ver'],
      [60, 'g', 'queso mozzarella rallado', 'lac'],
      ['Salsa de aguacate'],
      [1, 'u', 'aguacate|aguacates', 'ver'],
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
    ],
    pasos: [
      'Papas en cubitos con un chorrito de aceite y sal: freidora de aire a 200 °C por 15 minutos, moviéndolas a la mitad (o horno a 220 °C por 25 minutos).',
      'En una sartén, sofríe la cebolla picada, agrega la carne y el ajo y cocina hasta que dore. Sazona con comino, pimentón, salsa inglesa, sal y pimienta.',
      'Aparte, revuelve los huevos con sal a fuego bajo.',
      'Salsa: pisa el aguacate con el yogur, el jugo del limón y sal.',
      'Arma: tortilla + papas + carne + huevo + queso + cebolla larga picada. Enrolla y dora en la sartén 1 minuto por cada lado.',
    ],
    liv: 'Medio burrito con una fruta, o el relleno en plato sin tortilla.',
    salsas: ['salsa-aguacate'],
    mus: 'Un burrito entero y un vaso de leche o un batido.',
    adel: 'Se congelan envueltos en papel aluminio hasta por 1 mes. Se calientan sin el aluminio en la freidora a 180 °C por 8 a 10 minutos.',
    con: 'Café o chocolate sin azúcar y una fruta.',
  },
  {
    id: 'deditos-bang-bang', o: 'h4s', v: 'Y0buYRLicag',
    n: 'Deditos de pollo Bang Bang (salsa suave)', e: '🍤',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['freidora|horno'], t: 30, d: 'Fácil', kcal: 440, prot: 46,
    ing: [
      [800, 'g', 'filetes de pechuga de pollo (o pechuga en tiras)', 'car'],
      [0.5, 'taza', 'harina de trigo', 'gra'],
      [2, 'u', 'huevo|huevos', 'lac'],
      [3, 'taza', 'Corn Flakes sin azúcar', 'gra'],
      [1, 'cdta', 'ajo en polvo', 'bas'],
      [1, 'cdta', 'cebolla en polvo', 'bas'],
      [1, 'cdta', 'sal', 'bas'],
      [null, 'gusto', 'aceite en spray', 'bas'],
      ['Salsa Bang Bang'],
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [2, 'cda', 'mayonesa light', 'sal'],
      [3, 'cda', 'salsa agridulce (la de la comida china)', 'sal'],
      [1, 'cdta', 'miel de abejas', 'sal'],
    ],
    pasos: [
      'Sazona el pollo con sal, pimienta, ajo en polvo y cebolla en polvo.',
      'Arma 3 platos: harina, huevos batidos y Corn Flakes triturados con la mano.',
      'Pasa cada tira por harina, huevo y Corn Flakes, apretando bien.',
      'Rocía con aceite en spray. Freidora de aire a 200 °C por 10 a 12 minutos, volteando a la mitad (horno: 220 °C por 18 a 20 minutos).',
      'Salsa: mezcla el yogur, la mayonesa, la salsa agridulce, la miel y una pizca de sal. Sirve los deditos con la salsa para untar.',
    ],
    liv: 'En la salsa usa más yogur y nada de mayonesa. Acompaña con ensalada de pepino.',
    pica: 'La salsa original lleva sriracha y chile dulce: al que le guste picante, que le ponga una cucharadita de sriracha a su salsa.',
    salsas: ['salsa-bang-bang', 'salsa-miel-mostaza'],
    mus: 'Porción y media de pollo con arroz o papa criolla.',
    adel: 'La salsa dura 5 días en la nevera. El pollo se puede apanar el día anterior.',
    con: 'Ensalada de pepino y tomate, o arroz.',
  },
  {
    id: 'muffins-huevo-papa', o: 'h4s', v: 'BCLq_5_1hpc',
    n: 'Muffins de huevo con base de papa crujiente', e: '🧁',
    m: ['desayuno'], p: 'huevo', a: ['horno'], t: 40, d: 'Media', kcal: 310, prot: 22,
    ing: [
      [2, 'u', 'papa pastusa mediana|papas pastusas medianas', 'ver'],
      [10, 'u', 'huevo|huevos', 'lac'],
      [0.5, 'u', 'pimentón rojo|pimentones rojos', 'ver'],
      [1, 'u', 'tallo de cebolla larga|tallos de cebolla larga', 'ver'],
      [1, 'taza', 'espinaca picada', 'ver'],
      [60, 'g', 'jamón (de pavo o de cerdo)', 'car'],
      [60, 'g', 'queso mozzarella rallado', 'lac'],
      [null, 'gusto', 'aceite en spray', 'bas'],
    ],
    pasos: [
      'Prende el horno a 190 °C y engrasa un molde para 12 muffins (los moldes de silicona también sirven).',
      'Ralla las papas, exprímelas con un trapo limpio para sacarles el agua y sazónalas con sal y un chorrito de aceite.',
      'Pon una capa de papa en el fondo de cada molde, apretando con una cuchara. Hornea 15 minutos hasta que dore: esa es la base crujiente.',
      'Bate los huevos con sal y pimienta. Agrega el pimentón, la cebolla larga, la espinaca, el jamón picado y el queso.',
      'Reparte la mezcla sobre las bases de papa y hornea 18 a 20 minutos más, hasta que el huevo esté firme.',
    ],
    liv: 'Dos muffins con una fruta es un desayuno de unas 300 calorías.',
    salsas: ['salsa-aguacate'],
    mus: 'Cuatro muffins con una arepa o pan integral y un vaso de leche.',
    adel: 'Duran 4 días en la nevera. Se calientan 5 minutos en la freidora de aire a 170 °C.',
    con: 'Una fruta y café.',
  },
  {
    id: 'muslos-glaseados', o: 'h4s', v: 'o0lF5SIDrkU',
    n: 'Muslos de pollo ahumados con glaseado de miel', e: '🍗',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['horno|freidora'], t: 45, d: 'Fácil', kcal: 470, prot: 40,
    ing: [
      [8, 'u', 'muslo de pollo|muslos de pollo', 'car'],
      [1, 'cda', 'pimentón ahumado (o pimentón normal)', 'sal'],
      [1, 'cdta', 'ajo en polvo', 'bas'],
      [1, 'cdta', 'cebolla en polvo', 'bas'],
      [1, 'cda', 'panela rallada', 'gra'],
      [1, 'cdta', 'sal', 'bas'],
      ['Glaseado'],
      [3, 'cda', 'miel de abejas', 'sal'],
      [2, 'cda', 'salsa BBQ', 'sal'],
      [1, 'cda', 'vinagre de manzana', 'sal'],
    ],
    pasos: [
      'Mezcla el pimentón ahumado, el ajo, la cebolla en polvo, la panela, la sal y pimienta. Unta bien los muslos por todos lados.',
      'Horno a 200 °C por 35 a 40 minutos, o freidora de aire a 190 °C por 22 a 25 minutos, volteando a la mitad.',
      'Mientras tanto mezcla la miel, la salsa BBQ y el vinagre.',
      'Los últimos 5 minutos, pinta los muslos con el glaseado y termina de cocinar hasta que brillen.',
      'Revisa que el jugo del pollo salga transparente al pincharlo cerca del hueso.',
    ],
    liv: 'Quítales la piel antes de cocinarlos y come un muslo con ensalada y media taza de arroz.',
    salsas: ['salsa-miel-mostaza'],
    mus: 'Dos muslos con una taza de arroz y ensalada.',
    adel: 'Adoba los muslos la noche anterior y guárdalos tapados en la nevera.',
    con: 'Papa criolla, arroz o ensalada de repollo.',
  },
  {
    id: 'tacos-big-mac', o: 'h4s', v: '-8xJgVk5iUs',
    n: 'Tacos Big Mac (carne en tortilla tostada)', e: '🌮',
    m: ['almuerzo', 'comida'], p: 'res', a: ['estufa'], t: 25, d: 'Fácil', kcal: 540, prot: 38,
    ing: [
      [500, 'g', 'carne molida de res magra', 'car'],
      [8, 'u', 'tortilla de trigo pequeña|tortillas de trigo pequeñas', 'pan'],
      [4, 'u', 'tajada de queso amarillo|tajadas de queso amarillo', 'lac'],
      [2, 'taza', 'lechuga picada', 'ver'],
      [0.5, 'u', 'cebolla cabezona|cebollas cabezonas', 'ver'],
      [4, 'u', 'pepinillo encurtido|pepinillos encurtidos', 'sal'],
      ['Salsa Big Mac'],
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [2, 'cda', 'mayonesa light', 'sal'],
      [1, 'cda', 'mostaza (normal)', 'sal'],
      [1, 'cda', 'salsa de tomate', 'sal'],
      [0.5, 'cdta', 'ajo en polvo', 'bas'],
      [0.5, 'cdta', 'cebolla en polvo', 'bas'],
    ],
    pasos: [
      'Salsa: mezcla el yogur, la mayonesa, la mostaza, la salsa de tomate, 1 cucharada de pepinillos picados, un chorrito del vinagre del frasco de pepinillos, el ajo y la cebolla en polvo.',
      'Divide la carne en 8 bolitas. Aplasta cada bolita sobre una tortilla, en una capa delgada hasta el borde. Ponle sal y pimienta.',
      'Pon la tortilla en la sartén bien caliente con la carne hacia abajo, 3 a 4 minutos hasta que dore. Voltéala, pon media tajada de queso y deja 1 minuto más.',
      'Sirve con lechuga, cebolla picada, pepinillos y salsa. Dobla como un taco.',
    ],
    liv: 'Dos tacos con una ensalada grande, y la salsa solo con yogur (sin mayonesa).',
    salsas: ['salsa-big-mac'],
    mus: 'Tres tacos y un vaso de leche o de yogur griego.',
    adel: 'La salsa se puede hacer el día anterior y dura 5 días en la nevera.',
    con: 'Ensalada de lechuga y tomate.',
  },
  {
    id: 'pollo-mexicano-olla', o: 'h4s', v: 'xhwV8mYQoro',
    n: 'Pollo mexicano en olla lenta', e: '🌶️',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['olla'], t: 15, lento: '4 h en ALTO o 6 a 8 h en BAJO', d: 'Fácil', kcal: 420, prot: 55,
    ing: [
      [1000, 'g', 'pechuga de pollo sin hueso', 'car'],
      [3, 'u', 'tomate chonto|tomates chontos', 'ver'],
      [0.5, 'u', 'cebolla cabezona|cebollas cabezonas', 'ver'],
      [1, 'u', 'lata de frijoles rojos o negros (400 g)|latas de frijoles rojos o negros (400 g)', 'otr'],
      [1, 'taza', 'maíz tierno desgranado', 'otr'],
      [1, 'cda', 'comino', 'bas'],
      [1, 'cda', 'pimentón en polvo (paprika)', 'sal'],
      [1, 'cdta', 'ajo en polvo', 'bas'],
      [1, 'cdta', 'orégano seco', 'sal'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [null, 'gusto', 'cilantro', 'ver'],
    ],
    pasos: [
      'Pon las pechugas en la olla lenta (descongeladas, nunca congeladas). Sazona con comino, pimentón, ajo, orégano y sal.',
      'Licúa los tomates con la media cebolla y échalo encima, con los frijoles escurridos y el maíz.',
      'Tapa y cocina 4 horas en ALTO o 6 a 8 horas en BAJO. No destapes mientras se cocina.',
      'Desmecha el pollo con dos tenedores dentro de la olla y revuelve todo.',
      'Termina con el jugo del limón y cilantro picado. Sirve en tazón con arroz, en tacos o con arepa.',
    ],
    liv: 'Sírvelo sobre lechuga picada en vez de arroz.',
    pica: 'Al que le guste picante: jalapeños o ají en su plato.',
    salsas: ['guacamole-licuadora', 'salsa-aguacate'],
    mus: 'Porción grande de pollo con una taza de arroz.',
    adel: 'Rinde para dos comidas y dura 4 días en la nevera. También se congela.',
    con: 'Arroz, arepa o guacamole.',
  },
  {
    id: 'tazon-pollo-pegajoso', o: 'h4s', v: 'WvvWT8krk7o',
    n: 'Tazón de pollo pegajoso con batata', e: '🍠',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['estufa', 'freidora|horno'], t: 35, d: 'Fácil', kcal: 450, prot: 47,
    ing: [
      [800, 'g', 'pechuga de pollo sin hueso', 'car'],
      [2, 'u', 'batata mediana|batatas medianas', 'ver'],
      [1, 'cdta', 'pimentón en polvo (paprika)', 'sal'],
      [2, 'taza', 'brócoli en arbolitos', 'ver'],
      ['Salsa pegajosa'],
      [3, 'cda', 'salsa soya baja en sodio', 'sal'],
      [3, 'cda', 'miel de abejas', 'sal'],
      [2, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'jengibre fresco rallado', 'ver'],
      [1, 'cdta', 'fécula de maíz (Maizena)', 'gra'],
      [1, 'u', 'tallo de cebolla larga|tallos de cebolla larga', 'ver'],
      [null, 'gusto', 'ajonjolí (opcional)', 'sal'],
    ],
    pasos: [
      'Pela la batata y córtala en cubos. Mézclala con un chorrito de aceite, sal y pimentón. Freidora de aire a 200 °C por 18 a 20 minutos (horno: 220 °C por 25 minutos).',
      'Corta el pollo en cubos y dóralo en una sartén con poco aceite, 6 a 8 minutos.',
      'Mezcla la soya, la miel, el ajo picado, el jengibre y la Maizena disuelta en 2 cucharadas de agua. Échala al pollo y deja 2 minutos hasta que espese y brille.',
      'Cocina el brócoli al vapor o en agua hirviendo 4 a 5 minutos.',
      'Sirve en tazón: batata, pollo pegajoso, brócoli, cebolla larga picada y ajonjolí.',
    ],
    liv: 'Media batata, doble brócoli y solo 1 cucharada de miel en la salsa.',
    pica: 'Al que le guste picante: unas gotas de sriracha en su tazón.',
    salsas: ['salsa-yogur-ajo'],
    mus: 'Doble pollo y la batata completa.',
    adel: 'La batata y el pollo se pueden dejar listos para 3 días. La salsa se agrega al calentar.',
    con: 'Ya es plato completo.',
  },
  {
    id: 'tenders-limon-pimienta', o: 'h4s', v: 'jdXtavlNgDk',
    n: 'Tenders de pollo al limón y pimienta con salsa de yogur', e: '🍋',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['freidora|horno'], t: 30, d: 'Fácil', kcal: 380, prot: 48,
    ing: [
      [800, 'g', 'filetes de pechuga de pollo (o pechuga en tiras)', 'car'],
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [2, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [1, 'taza', 'miga de pan o apanadura', 'gra'],
      [1, 'cdta', 'pimienta negra molida', 'bas'],
      [1, 'cdta', 'ajo en polvo', 'bas'],
      [1, 'cdta', 'sal', 'bas'],
      [null, 'gusto', 'aceite en spray', 'bas'],
      ['Salsa de yogur'],
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'cda', 'perejil fresco picado', 'ver'],
      [1, 'u', 'diente de ajo|dientes de ajo', 'ver'],
    ],
    pasos: [
      'Mezcla media taza de yogur con el jugo de un limón, la ralladura de los dos limones, sal y pimienta. Unta el pollo y deja 15 minutos (o toda la noche en la nevera).',
      'En un plato mezcla la miga de pan con el resto de la pimienta, el ajo en polvo y una pizca de sal.',
      'Saca cada tira del yogur y pásala por la miga de pan, apretando bien.',
      'Rocía con aceite en spray. Freidora de aire a 200 °C por 10 a 12 minutos, volteando a la mitad (horno: 220 °C por 18 minutos).',
      'Salsa: mezcla el otro medio de yogur con el jugo del segundo limón, el perejil, el ajo bien picadito y sal.',
    ],
    liv: 'Con ensalada grande y la salsa de yogur: es de las recetas más livianas.',
    salsas: ['salsa-yogur-ajo', 'salsa-ranch'],
    mus: 'Porción y media de pollo con arroz o papa criolla.',
    adel: 'Deja el pollo marinando en yogur desde la noche anterior: queda más jugoso.',
    con: 'Ensalada o papa criolla.',
  },
  {
    id: 'tazon-carne-criolla', o: 'h4s', v: 'l13R0L1FQBA',
    n: 'Tazón de carne con papa criolla y salsa de aguacate', e: '🥑',
    m: ['almuerzo', 'comida'], p: 'res', a: ['estufa', 'freidora|horno', 'licuadora'], t: 35, d: 'Fácil', kcal: 475, prot: 32,
    ing: [
      [500, 'g', 'carne molida de res magra', 'car'],
      [600, 'g', 'papa criolla', 'ver'],
      [0.5, 'u', 'cebolla cabezona|cebollas cabezonas', 'ver'],
      [2, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'comino', 'bas'],
      [1, 'cdta', 'pimentón en polvo (paprika)', 'sal'],
      [2, 'u', 'tomate chonto|tomates chontos', 'ver'],
      [2, 'taza', 'lechuga picada', 'ver'],
      ['Salsa de aguacate (licuadora)'],
      [1, 'u', 'aguacate|aguacates', 'ver'],
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [null, 'gusto', 'cilantro', 'ver'],
    ],
    pasos: [
      'Parte las papas criollas por la mitad, échales un chorrito de aceite y sal. Freidora de aire a 200 °C por 18 a 20 minutos, moviéndolas a la mitad.',
      'En una sartén sofríe la cebolla picada y el ajo, agrega la carne y cocina hasta que dore. Sazona con comino, pimentón, sal y pimienta.',
      'Salsa: licúa el aguacate, el yogur, el jugo del limón, un puñado de cilantro, sal y 2 o 3 cucharadas de agua hasta que quede cremosa.',
      'Arma el tazón: lechuga, papas, carne, tomate picado y la salsa por encima.',
    ],
    liv: 'De 6 a 8 papitas por plato y doble lechuga.',
    salsas: ['salsa-aguacate', 'salsa-pimenton-asado'],
    mus: 'Porción y media de carne y de 10 a 12 papitas criollas.',
    adel: 'La carne y las papas duran 4 días en la nevera. La salsa, mejor el mismo día (se oscurece).',
    con: 'Ya es plato completo.',
  },
  {
    id: 'tacos-pollo-chipotle', o: 'h4s', v: 'ArWKo3-vJqs',
    n: 'Tacos de pollo desmechado con salsa ahumada', e: '🌮',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['estufa', 'licuadora'], t: 40, d: 'Fácil', kcal: 370, prot: 44,
    ing: [
      [700, 'g', 'pechuga de pollo sin hueso', 'car'],
      [1, 'u', 'cebolla cabezona|cebollas cabezonas', 'ver'],
      [2, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'comino', 'bas'],
      [1, 'cdta', 'pimentón en polvo (paprika)', 'sal'],
      [8, 'u', 'tortilla pequeña de maíz o trigo|tortillas pequeñas de maíz o trigo', 'pan'],
      [1, 'taza', 'repollo morado picado', 'ver'],
      [null, 'gusto', 'cilantro', 'ver'],
      ['Salsa ahumada (licuadora)'],
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'cdta', 'pimentón ahumado (no pica)', 'sal'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
    ],
    pasos: [
      'Cocina el pollo en agua con media cebolla, el ajo y sal por 20 minutos. Sácalo y desméchalo con dos tenedores.',
      'En una sartén con poco aceite, saltea el pollo desmechado con comino, pimentón y un chorrito del caldo, 3 minutos.',
      'Salsa: licúa el yogur, el pimentón ahumado, el jugo del limón y sal.',
      'Calienta las tortillas en la sartén seca.',
      'Arma: tortilla, pollo, repollo, cebolla picada, cilantro y salsa.',
    ],
    liv: 'Dos tacos con bastante repollo, en tortilla de maíz.',
    pica: 'La original lleva chile chipotle (pica): al que le guste, que licúe uno en su porción de salsa.',
    salsas: ['salsa-pimenton-asado', 'guacamole-licuadora'],
    mus: 'Tres o cuatro tacos con bastante pollo.',
    adel: 'El pollo desmechado dura 4 días en la nevera. Guarda el caldo para sopas o arroz.',
    con: 'Guacamole en licuadora.',
  },
  {
    id: 'tazon-carne-chipotle', o: 'h4s', vq: 'hunt4shredz high protein beef potato bowl',
    n: 'Tazón de carne con papa y salsa de pimentón asado', e: '🌶️',
    m: ['almuerzo', 'comida'], p: 'res', a: ['estufa', 'freidora|horno', 'licuadora'], t: 40, d: 'Media', kcal: 440, prot: 31,
    ing: [
      [500, 'g', 'carne molida de res magra', 'car'],
      [3, 'u', 'papa pastusa mediana|papas pastusas medianas', 'ver'],
      [1, 'cdta', 'comino', 'bas'],
      [1, 'cdta', 'ajo en polvo', 'bas'],
      [1, 'taza', 'maíz tierno desgranado', 'otr'],
      [2, 'taza', 'lechuga picada', 'ver'],
      [0.5, 'u', 'cebolla morada|cebollas moradas', 'ver'],
      ['Salsa de pimentón asado (licuadora)'],
      [1, 'u', 'pimentón rojo|pimentones rojos', 'ver'],
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'cdta', 'pimentón ahumado (no pica)', 'sal'],
      [1, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
    ],
    pasos: [
      'Papas en cubos con un chorrito de aceite y sal: freidora de aire a 200 °C por 18 a 20 minutos (horno: 220 °C por 25 a 30 minutos).',
      'Asa el pimentón entero en la freidora (200 °C, 10 a 12 minutos) o directo en la llama de la estufa, hasta que la piel se ponga negra. Mételo en una bolsa 5 minutos y pélalo.',
      'Salsa: licúa el pimentón asado (sin semillas), el yogur, el pimentón ahumado, el ajo, el jugo del limón y sal.',
      'Dora la carne en una sartén con comino, ajo en polvo, sal y pimienta. Agrega el maíz al final.',
      'Arma el tazón: lechuga, papas, carne con maíz, cebolla morada picada y la salsa por encima.',
    ],
    liv: 'Una papa pequeña por plato y más lechuga.',
    pica: 'Al que le guste picante: un chile chipotle en adobo licuado en su salsa.',
    salsas: ['salsa-pimenton-asado', 'salsa-aguacate'],
    mus: 'Porción y media de carne y una papa más.',
    adel: 'La salsa dura 5 días en la nevera. La carne y la papa, 4 días.',
    con: 'Ya es plato completo.',
  },
  {
    id: 'guacamole-licuadora', o: 'h4s', v: 'TWGTu8SRY2I', fv: 'hq3',
    n: 'Guacamole en licuadora', e: '🥑',
    m: ['salsa'], p: 'salsa', a: ['licuadora'], t: 10, d: 'Fácil', kcal: 180, prot: 2,
    ing: [
      [3, 'u', 'aguacate|aguacates', 'ver'],
      [2, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [0.25, 'u', 'cebolla morada|cebollas moradas', 'ver'],
      [1, 'u', 'tomate chonto|tomates chontos', 'ver'],
      [1, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [null, 'gusto', 'cilantro', 'ver'],
    ],
    pasos: [
      'Licúa primero el jugo de los limones, la cebolla, el ajo, el cilantro y sal.',
      'Agrega la pulpa de los aguacates y licúa con pulsos cortos (prender y apagar) para que quede con textura, no como puré.',
      'Pásalo a un tazón y agrega el tomate picado en cubitos.',
      'Tápalo con plástico pegado al guacamole para que no se ponga negro.',
    ],
    liv: 'Dos cucharadas por plato son suficientes: es sano pero tiene muchas calorías.',
    pica: 'Al que le guste picante: un pedacito de jalapeño o ají en su porción.',
    adel: 'Mejor hacerlo el mismo día.',
    con: 'Tacos, burritos, carne desmechada o pollo mexicano.',
  },
  {
    id: 'ensalada-pollo-proteina', o: 'h4s', vq: 'hunt4shredz high protein chicken salad',
    n: 'Ensalada de pollo alta en proteína', e: '🥗',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['estufa'], t: 30, d: 'Fácil', kcal: 260, prot: 40,
    ing: [
      [600, 'g', 'pechuga de pollo sin hueso', 'car'],
      [1, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'cda', 'mostaza (normal)', 'sal'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [2, 'u', 'tallo de apio|tallos de apio', 'ver'],
      [1, 'u', 'manzana verde|manzanas verdes', 'ver'],
      [0.25, 'u', 'cebolla morada|cebollas moradas', 'ver'],
      [null, 'gusto', 'perejil fresco picado', 'ver'],
      [4, 'u', 'hoja grande de lechuga|hojas grandes de lechuga', 'ver'],
    ],
    pasos: [
      'Cocina el pollo en agua con sal, un diente de ajo y un pedazo de cebolla por 20 minutos. Déjalo enfriar y córtalo en cubitos o desméchalo.',
      'Pica el apio, la manzana (con cáscara) y la cebolla morada bien pequeñitos.',
      'Mezcla el yogur con la mostaza, el jugo del limón, sal y pimienta.',
      'Revuelve el pollo, las verduras, la manzana y la salsa. Agrega perejil.',
      'Déjala en la nevera 20 minutos y sírvela sobre hojas de lechuga, en pan integral o con arepa.',
    ],
    liv: 'Sobre hojas de lechuga, sin pan ni arepa.',
    salsas: ['vinagreta-limon', 'salsa-ranch'],
    mus: 'Doble porción de pollo, en pan integral o con arepa.',
    adel: 'Dura 3 días en la nevera. Puedes usar pollo que sobró de otra receta.',
    con: 'Pan integral, arepa o galletas integrales.',
  },
  {
    id: 'hot-pockets-buffalo', o: 'h4s', vq: 'hunt4shredz buffalo chicken hot pocket',
    n: 'Hot pockets de pollo con queso y BBQ', e: '🥟',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['freidora|horno'], t: 30, d: 'Media', kcal: 435, prot: 43,
    ing: [
      [500, 'g', 'pechuga de pollo sin hueso', 'car'],
      [3, 'cda', 'salsa BBQ', 'sal'],
      [0.25, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'cdta', 'ajo en polvo', 'bas'],
      [80, 'g', 'queso mozzarella rallado', 'lac'],
      [4, 'u', 'tortilla de trigo grande|tortillas de trigo grandes', 'pan'],
      [1, 'u', 'huevo|huevos', 'lac'],
      [1, 'u', 'tallo de cebolla larga|tallos de cebolla larga', 'ver'],
    ],
    pasos: [
      'Cocina el pollo en agua con sal 20 minutos y desméchalo (o usa pollo que haya sobrado).',
      'Mezcla el pollo con la salsa BBQ, el yogur, el ajo en polvo, el queso y la cebolla larga picada.',
      'Pon una porción en el centro de cada tortilla. Dobla los 4 lados hacia el centro, como un sobre, y voltéalo con el doblez hacia abajo.',
      'Píntalos con huevo batido. Freidora de aire a 190 °C por 6 a 8 minutos hasta que doren (horno: 200 °C por 12 a 15 minutos).',
    ],
    liv: 'Un hot pocket con palitos de apio y zanahoria.',
    pica: 'La original es con salsa buffalo (picante): al que le guste, que use buffalo en vez de BBQ en el suyo.',
    salsas: ['salsa-ranch', 'salsa-yogur-ajo'],
    mus: 'Dos hot pockets y un vaso de leche.',
    adel: 'Se arman el día anterior y se guardan crudos en la nevera, o se congelan.',
    con: 'Palitos de apio y zanahoria con salsa de yogur.',
  },

  // ───────────── Desayunos, snacks y postres (videos que manda Juan) ─────────────
  {
    id: 'avena-brownie', o: 'fb', vu: 'https://www.facebook.com/watch/?v=2182763055620129', de: 'Alejandro Méndez García', foto: 'fotos/avena-brownie.jpg',
    n: 'Avena trasnochada de brownie', e: '🍫',
    m: ['desayuno', 'postre'], p: 'lacteo', a: [], t: 10, reposo: 'toda la noche en la nevera (si hay afán, mínimo 15 minutos)', d: 'Fácil', kcal: 315, prot: 17,
    ing: [
      [2, 'taza', 'avena en hojuelas', 'gra'],
      [6, 'cda', 'cacao en polvo sin azúcar', 'sal'],
      [4, 'cda', 'stevia granulada (o al gusto)', 'sal'],
      [2, 'taza', 'leche descremada o deslactosada', 'lac'],
      [1, 'cdta', 'esencia de vainilla', 'sal'],
      [null, 'gusto', 'pizca de sal gruesa', 'bas'],
      [4, 'cda', 'chispas de chocolate semiamargo', 'otr'],
      ['Cubierta cremosa (tipo frosting)'],
      [1, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [2, 'cda', 'cacao en polvo sin azúcar', 'sal'],
      [2, 'cda', 'stevia granulada (o al gusto)', 'sal'],
      [0.5, 'cdta', 'esencia de vainilla', 'sal'],
    ],
    pasos: [
      'En un tazón mezcla en seco la avena, el cacao y la stevia, para que el cacao no haga grumos.',
      'Agrega la leche, unas gotas de vainilla y una pizca de sal gruesa (la sal es lo que le da el sabor a brownie). Mezcla muy bien.',
      'Agrega la mitad de las chispas de chocolate y reparte en frascos o vasos con tapa, uno por persona.',
      'Cubierta: mezcla el yogur griego con el cacao, la stevia y la vainilla hasta que quede cremoso, como un frosting.',
      'Pon la cubierta encima de cada frasco y termina con el resto de las chispas.',
      'Tapa y deja en la nevera toda la noche (si hay afán, mínimo 15 minutos). Se come fría.',
    ],
    liv: 'Media taza de avena por persona, con leche descremada y sin chispas de chocolate (o solo unas poquitas encima).',
    mus: 'El frasco completo como en el video: 1 taza de avena con 1 taza de leche (o leche con proteína) y la cubierta de yogur. Sirve antes del gimnasio.',
    adel: 'Se arman la noche anterior y duran hasta 3 días tapadas en la nevera: puedes dejar listos los desayunos de varios días.',
    con: 'Un café o una fruta. También sirve de postre o de algo para el antojo.',
  },

  {
    id: 'pancakes-pie-limon', o: 'fb', vu: 'https://www.facebook.com/watch/?v=1569074414527561', de: 'Alejandro Méndez García', foto: 'fotos/pancakes-pie-limon.jpg',
    n: 'Pancakes de avena sabor pie de limón', e: '🥞',
    m: ['desayuno', 'postre'], p: 'huevo', a: ['estufa'], t: 25, d: 'Fácil', kcal: 330, prot: 19,
    ing: [
      [4, 'u', 'huevo|huevos', 'lac'],
      [2, 'cda', 'mantequilla derretida (o ghee, o aceite de coco)', 'lac'],
      [1, 'cdta', 'esencia de vainilla', 'sal'],
      [2, 'cda', 'stevia granulada (o al gusto)', 'sal'],
      [null, 'gusto', 'pizca de sal gruesa', 'bas'],
      [3, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [2, 'taza', 'harina de avena (o avena en hojuelas licuada)', 'gra'],
      [1, 'taza', 'leche descremada o deslactosada', 'lac'],
      [2, 'cdta', 'polvo de hornear', 'gra'],
      ['Crema de limón'],
      [1, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [0.5, 'cdta', 'esencia de vainilla', 'sal'],
      [1, 'cda', 'stevia granulada (o al gusto)', 'sal'],
      ['Para decorar (opcional)'],
      [null, 'gusto', 'avena tostada o galleta triturada (opcional)', 'gra'],
    ],
    pasos: [
      'En un tazón bate los huevos hasta que hagan burbujas.',
      'Agrega la mantequilla derretida (o ghee, o aceite de coco), la vainilla, la stevia y una pizca de sal gruesa.',
      'Exprime el jugo de un limón en la mezcla. Guarda otro limón para la crema y el tercero para decorar.',
      'Agrega la harina de avena y mezcla; luego la leche. Debe quedar espesa pero que caiga de la cuchara. Si no tienes harina de avena, licúa avena en hojuelas hasta que quede como harina.',
      'Por último agrega el polvo de hornear y la ralladura de un limón, y mezcla hasta que no queden grumos.',
      'Crema: mezcla el yogur griego con la vainilla, la stevia y el jugo del segundo limón. Métela a la nevera mientras haces los pancakes.',
      'El secreto es el fuego: sartén antiadherente a fuego medio-bajo. Echa un cucharón de mezcla y tapa. Cuando salgan burbujitas encima, voltéalo y deja 1 o 2 minutos más.',
      'Arma una torre: pancake, crema, pancake, crema. Termina con crema, ralladura de limón y rodajas de limón encima.',
    ],
    liv: 'Dos pancakes por persona (no la torre entera) con la crema de yogur, y sin mantequilla extra en la sartén: con sartén antiadherente no hace falta.',
    mus: 'La torre de 4 pancakes con bastante crema de yogur griego. Para más proteína, una clara de huevo más en la mezcla.',
    adel: 'La crema se puede dejar lista la noche anterior. Los pancakes duran 3 días en la nevera y se calientan en la sartén o en la freidora (160 °C, 3 minutos).',
    con: 'Un café o una fruta. Con la crema y el limón sabe a pie de limón: también sirve de postre.',
  },

  {
    id: 'avena-chocotorta', o: 'fb', vu: 'https://www.facebook.com/watch/?v=1714383666437769', de: 'Pau Moguilevsky (pulicocina)', foto: 'fotos/avena-chocotorta.jpg',
    n: 'Avena horneada chocotorta con arequipe', e: '🍰',
    m: ['desayuno', 'postre'], p: 'lacteo', a: ['horno|freidora'], t: 45, d: 'Fácil', kcal: 290, prot: 12,
    ing: [
      [2, 'u', 'banano maduro|bananos maduros', 'ver'],
      [2, 'taza', 'avena en hojuelas', 'gra'],
      [2, 'cda', 'cacao en polvo sin azúcar', 'sal'],
      [1, 'cdta', 'polvo de hornear', 'gra'],
      [1, 'cda', 'stevia granulada (o 2 cucharadas de miel)', 'sal'],
      [2, 'taza', 'leche descremada o deslactosada', 'lac'],
      [60, 'g', 'proteína en polvo (opcional)', 'otr'],
      ['Cobertura'],
      [2, 'cda', 'queso crema o yogur griego', 'lac'],
      [1, 'cda', 'arequipe (mejor sin azúcar)', 'sal'],
      [null, 'gusto', 'chocolate derretido para decorar (opcional)', 'otr'],
    ],
    pasos: [
      'Prende el horno a 180 °C. Engrasa un molde o refractaria de unos 15 a 18 cm por lado.',
      'En el mismo molde pisa los bananos con un tenedor hasta que queden en puré (también sirven 2 manzanas o peras en puré).',
      'Agrega la avena, el cacao, el polvo de hornear, la stevia (o la miel), la proteína en polvo si vas a usar, y la leche. Mezcla muy bien hasta que todo quede integrado.',
      'Horno a 180 °C por 35 a 40 minutos, o freidora de aire a 180 °C por unos 20 minutos. Está lista cuando al meter un cuchillo no sale masa pegada. Queda húmeda por dentro: eso es normal.',
      'Déjala enfriar un rato. Cobertura: mezcla el queso crema (o el yogur griego) con el arequipe y úntalo encima.',
      'Si quieres, decora con un hilito de chocolate derretido. Córtala en porciones y guárdala tapada en la nevera.',
    ],
    liv: 'Un cuarto de la torta por persona, con yogur griego en vez de queso crema, arequipe sin azúcar y sin el chocolate de encima.',
    mus: 'Con la proteína en polvo en la mezcla (o leche en polvo), porción y media y un vaso de leche.',
    adel: 'Se hace un día y queda para toda la semana: dura 4 o 5 días tapada en la nevera. Se come fría o tibia.',
    con: 'Un café o un vaso de leche. También sirve de postre.',
  },

  {
    id: 'volcan-chocolate-cottage', o: 'fb', vu: 'https://www.facebook.com/watch/?v=1521874895906563', de: 'Shred Happens', ingles: true, foto: 'fotos/volcan-chocolate.jpg',
    n: 'Volcán de chocolate con queso cottage', e: '🌋',
    m: ['postre'], p: 'lacteo', a: ['horno', 'licuadora'], t: 45, d: 'Fácil', kcal: 200, prot: 21,
    ing: [
      [450, 'g', 'queso cottage (o requesón)', 'lac'],
      [4, 'u', 'huevo|huevos', 'lac'],
      [6, 'cda', 'cacao en polvo sin azúcar', 'sal'],
      [8, 'cda', 'stevia granulada (o al gusto)', 'sal'],
      [1, 'cdta', 'esencia de vainilla', 'sal'],
      [4, 'cda', 'chispas de chocolate semiamargo', 'otr'],
    ],
    pasos: [
      'Prende el horno a 180 °C.',
      'Licúa el queso cottage hasta que quede liso, sin grumitos. Pásalo a un recipiente que sirva para horno (2 medianos, o tacitas individuales).',
      'Agrega los huevos, el cacao, la stevia y un chorrito de vainilla, y mezcla hasta que quede una masa lisa. La stevia tiene que ser en polvo o granulada, no líquida: eso es clave.',
      'Riega las chispas de chocolate encima y mueve el recipiente para que se hundan un poco: así el centro queda derretido, como un volcán.',
      'Hornea de 33 a 35 minutos (en tacitas individuales, de 20 a 25). Está listo cuando los bordes están firmes y el centro todavía tiembla un poquito.',
      'Déjalo reposar 2 o 3 minutos y cómetelo tibio.',
    ],
    liv: 'Ya es liviano: unas 200 calorías por porción. Con pocas chispas de chocolate (o sin ellas) queda todavía más liviano.',
    mus: 'Doble porción para ti: unos 40 g de proteína. Sirve de postre o después del gimnasio.',
    adel: 'La mezcla se puede dejar lista en la nevera desde la mañana y hornearla en la noche. Ya horneado dura 3 días en la nevera: se come frío o se calienta 5 minutos en el horno o la freidora.',
    con: 'Unas fresas o una cucharada de yogur griego encima.',
  },

  {
    id: 'cheesecake-chocolate-proteico', o: 'fb', vu: 'https://www.facebook.com/share/r/19fCgCBAUD/', de: 'theChefoutWest', ingles: true, foto: 'fotos/cheesecake-chocolate.jpg',
    n: 'Cheesecake de chocolate alto en proteína', e: '🍫',
    m: ['postre', 'desayuno'], p: 'lacteo', a: ['horno', 'licuadora'], t: 15, reposo: 'mínimo 8 horas en la nevera (mejor toda la noche)', d: 'Fácil', kcal: 300, prot: 19,
    ing: [
      [1, 'taza', 'queso cottage (o requesón)', 'lac'],
      [1, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [2, 'u', 'huevo|huevos', 'lac'],
      [0.5, 'taza', 'cacao en polvo sin azúcar', 'sal'],
      [0.5, 'taza', 'miel de abejas (o miel de maple)', 'sal'],
      [0.5, 'taza', 'harina de avena (o de almendras)', 'gra'],
      [2, 'cdta', 'esencia de vainilla', 'sal'],
    ],
    pasos: [
      'Prende el horno a 165 °C. Forra con papel de hornear un molde redondo pequeño (unos 15 cm).',
      'Echa todo en la licuadora: el queso cottage, el yogur, los huevos, el cacao, la miel, la harina de avena y la vainilla. Licúa hasta que quede completamente liso, raspando los lados si hace falta.',
      'Vierte la mezcla en el molde y alisa la superficie.',
      'Hornea de 45 a 50 minutos. Los bordes deben quedar firmes y el centro todavía blandito, que tiemble un poco. Se ve medio crudo en el medio y es lo correcto.',
      'Déjalo enfriar y llévalo a la nevera mínimo 8 horas, mejor toda la noche. Ahí el centro se endurece y queda cremoso, tipo fudge.',
      'Córtalo en 4 porciones y sírvelo frío.',
    ],
    liv: 'Un cuarto del cheesecake por persona, o hasta la mitad de una porción con una fruta. Si lo haces con menos miel (unas 4 cucharadas) queda menos dulce y más liviano.',
    mus: 'Una porción grande (la mitad del cheesecake) tiene unos 40 g de proteína. Sirve de desayuno o después del gimnasio.',
    adel: 'Se prepara la noche anterior y dura 4 o 5 días tapado en la nevera. Puedes dejar listos varios desayunos o postres de una vez.',
    con: 'Unas fresas o frambuesas encima, o un poquito de yogur griego.',
  },

  {
    id: 'postre-snickers-proteico', o: 'fb', vu: 'https://www.facebook.com/share/r/1AFwWwAxgs/', de: 'Cooksana Meals', foto: 'fotos/postre-snickers.jpg',
    n: 'Frasco desayuno tipo Snickers alto en proteína', e: '🥜',
    m: ['desayuno', 'postre'], p: 'lacteo', a: ['horno'], t: 30, reposo: 'toda la noche en la nevera', d: 'Media', kcal: 900, prot: 55,
    ing: [
      ['Base (4 frascos de 500 ml)'],
      [4, 'u', 'banano maduro|bananos maduros', 'ver'],
      [120, 'g', 'avena en hojuelas', 'gra'],
      [4, 'u', 'huevo|huevos', 'lac'],
      [4, 'cdta', 'cacao en polvo sin azúcar', 'sal'],
      [2, 'cdta', 'polvo de hornear', 'gra'],
      ['Crema'],
      [700, 'g', 'yogur griego natural sin azúcar', 'lac'],
      [110, 'g', 'proteína en polvo sabor vainilla (opcional)', 'otr'],
      [40, 'g', 'mantequilla de maní', 'otr'],
      ['Cubierta'],
      [70, 'g', 'mantequilla de maní (para derretir y chorrear)', 'otr'],
      [50, 'g', 'maní tostado picado', 'otr'],
      [70, 'g', 'chocolate semiamargo', 'otr'],
      [2, 'cdta', 'aceite de coco (opcional)', 'bas'],
    ],
    pasos: [
      'Base: en un recipiente pisa los bananos y mézclalos con los huevos. Agrega la avena, el cacao y el polvo de hornear, y mezcla hasta que todo quede integrado.',
      'Reparte la masa en el fondo de 4 frascos o recipientes de 500 ml. Cocina cada uno en el microondas de 2 a 3 minutos, o hornea a 180 °C de 10 a 15 minutos.',
      'Deja la base enfriar por completo antes de seguir.',
      'Crema: mezcla el yogur griego con la proteína en polvo y la mantequilla de maní hasta que quede lisa y cremosa. Extiéndela sobre cada base fría.',
      'Cubierta: derrite la mantequilla de maní unos segundos y chorréala por encima. Riega el maní picado.',
      'Derrite el chocolate con el aceite de coco (a baño de María o en el microondas de a 20 segundos) y viértelo sobre cada frasco.',
      'Tapa y deja en la nevera toda la noche. Amanece listo para el desayuno.',
    ],
    liv: 'Es una comida fuerte (cada frasco tiene unas 900 calorías con la proteína en polvo). Para bajar de peso: media porción, sin la mantequilla de maní de la cubierta y con la mitad del chocolate.',
    mus: 'El frasco completo, como en la receta: unos 55 g de proteína con la proteína en polvo (unos 35 g sin ella). Perfecto de desayuno antes del gimnasio.',
    adel: 'Se prepara la noche anterior, y puedes dejar listos varios frascos: duran 3 o 4 días tapados en la nevera.',
    con: 'Con un café. Si no consigues proteína en polvo, déjala por fuera: queda igual de rico, con menos proteína. El yogur griego puede ser skyr.',
  },

  {
    id: 'brownies-frijol-negro', o: 'fb', vu: 'https://www.facebook.com/watch/?v=1375150824602933', de: 'Live Eat Learn (Sarah Bond, nutricionista)', ingles: true,
    fija: 'Una sola tanda: un molde de 16 brownies (no se parte a la mitad)',
    n: 'Brownies de frijol negro (sin harina)', e: '🍫',
    m: ['postre'], p: 'granos', a: ['horno', 'licuadora'], t: 55, d: 'Fácil', kcal: 120, prot: 4,
    ing: [
      [1, 'u', 'lata de frijol negro (425 g), enjuagada y escurrida|latas de frijol negro (425 g), enjuagadas y escurridas', 'otr'],
      [3, 'u', 'huevo|huevos', 'lac'],
      [3, 'cda', 'aceite vegetal (de girasol o canola)', 'bas'],
      [1, 'cdta', 'esencia de vainilla', 'sal'],
      [0.25, 'taza', 'cacao en polvo sin azúcar', 'sal'],
      [120, 'g', 'azúcar (o la mitad de azúcar y la mitad de stevia granulada)', 'gra'],
      [0.5, 'cdta', 'polvo de hornear', 'gra'],
      [0.25, 'cdta', 'sal', 'bas'],
      [60, 'g', 'chocolate semiamargo en chispas o picado', 'otr'],
      [1, 'cdta', 'café instantáneo (opcional)', 'sal'],
    ],
    pasos: [
      'Prende el horno a 175 °C. Engrasa un molde cuadrado de 20 a 23 cm y fórralo con papel de hornear.',
      'Enjuaga muy bien los frijoles negros enlatados y escúrrelos. Licúalos o procésalos hasta que quede una pasta; mientras más lisa, más suaves quedan los brownies.',
      'Pasa la pasta a un tazón grande y mézclala con los huevos, el aceite y la vainilla (o licúa todo junto, así queda más liso).',
      'En otro tazón mezcla el cacao, el azúcar, el polvo de hornear, la sal y el café si vas a usar. Agrégalo a la mezcla de frijoles y revuelve.',
      'Agrega las chispas de chocolate (guarda un puñado). Vierte la masa en el molde.',
      'Hornea de 30 a 40 minutos. A los 15 minutos riega el puñado de chocolate que guardaste encima. Están listos cuando los bordes se ven firmes y el centro apenas tiembla; el palillo puede salir un poco húmedo.',
      'Déjalos enfriar del todo antes de cortar en 16 cuadros.',
    ],
    liv: 'Un cuadro (y como mucho dos) de los 16, con una fruta. Con la mitad del azúcar cambiada por stevia salen todavía más livianos.',
    mus: 'Dos o tres brownies con un vaso de leche o un yogur griego: aportan proteína y fibra de los frijoles.',
    adel: 'Duran hasta 7 días en la nevera y 3 meses en el congelador. Haz una tanda el domingo y tienes postre para toda la semana.',
    con: 'Un vaso de leche, o con una cucharada de yogur griego encima. Nadie nota que lleva frijoles.',
  },

  {
    id: 'avena-pastel-zanahoria', o: 'fb', vu: 'https://www.facebook.com/watch/?v=38039968028927698', de: 'Lindsay Pleskot, nutricionista', ingles: true, foto: 'fotos/avena-pastel-zanahoria.jpg',
    fija: 'Una sola tanda: un molde de 8 porciones (no se parte a la mitad)',
    n: 'Avena horneada de pastel de zanahoria con crema de yogur', e: '🥕',
    m: ['desayuno', 'postre'], p: 'huevo', a: ['horno', 'licuadora'], t: 55, d: 'Fácil', kcal: 385, prot: 11,
    ing: [
      ['Avena horneada'],
      [1, 'taza', 'leche descremada o deslactosada', 'lac'],
      [2 / 3, 'taza', 'compota de manzana sin azúcar', 'otr'],
      [3, 'u', 'huevo|huevos', 'lac'],
      [2, 'cda', 'miel de abejas', 'sal'],
      [2, 'cda', 'aceite de oliva', 'bas'],
      [2, 'cdta', 'esencia de vainilla', 'sal'],
      [2.5, 'taza', 'avena en hojuelas', 'gra'],
      [2, 'cdta', 'canela en polvo', 'bas'],
      [2, 'cdta', 'polvo de hornear', 'gra'],
      [1, 'cdta', 'bicarbonato de sodio', 'gra'],
      [0.75, 'cdta', 'sal', 'bas'],
      [1.5, 'taza', 'zanahoria rallada (sin pelar)', 'ver'],
      [0.5, 'taza', 'uvas pasas', 'otr'],
      ['Crema de yogur y queso crema'],
      [250, 'g', 'queso crema (de barra)', 'lac'],
      [2 / 3, 'taza', 'yogur griego natural', 'lac'],
      [0.25, 'taza', 'miel de abejas', 'sal'],
      [2, 'cdta', 'esencia de vainilla', 'sal'],
    ],
    pasos: [
      'Prende el horno a 190 °C. Engrasa un molde cuadrado de 23 cm (9 x 9 pulgadas) y fórralo con papel de hornear.',
      'Licúa la leche, la compota de manzana, los huevos, la miel, el aceite de oliva y la vainilla. Agrega la avena, la canela, el polvo de hornear, el bicarbonato y la sal, y licúa de nuevo hasta que la avena quede como harina y la masa lisa. Así sale suave, como un pastel y no como avena mojada.',
      'Pasa la masa a un tazón y mezcla con la zanahoria rallada y las uvas pasas. No hace falta pelar las zanahorias.',
      'Vierte en el molde y hornea de 30 a 40 minutos (a los 35 suele quedar perfecto), hasta que el centro esté firme.',
      'Déjala enfriar del todo antes de poner la crema: si la cubres caliente, la crema se derrite.',
      'Crema: licúa el queso crema, el yogur griego, la miel y la vainilla hasta que quede lisa. Extiéndela gruesa encima (la autora dice que ayuda con el azúcar en la sangre) y corta en 8 porciones.',
    ],
    liv: 'Una porción con la crema. Sin la crema son unas 230 calorías: si la quitas, ponle un poco de yogur griego y una cucharadita de miel.',
    mus: 'Dos porciones con un vaso de leche o un yogur griego: unos 22 g de proteína solo con la avena y los huevos.',
    adel: 'Se prepara en unos 20 minutos y alcanza para toda la semana: dura 5 días en la nevera, tapada y con la crema aparte o ya puesta.',
    con: 'Un café o una fruta.',
  },

  {
    id: 'avena-zanahoria-proteica', o: 'fb', vu: 'https://www.facebook.com/watch/?v=2331510814253401', de: 'Rooted with Syd', ingles: true, foto: 'fotos/avena-zanahoria-proteica.jpg',
    n: 'Avena horneada de zanahoria alta en proteína (con cubierta de cottage)', e: '🥕',
    m: ['desayuno', 'postre'], p: 'huevo', a: ['horno'], t: 50, d: 'Fácil', kcal: 470, prot: 34,
    ing: [
      ['Avena horneada'],
      [2, 'u', 'banano maduro|bananos maduros (2 a 3)', 'ver'],
      [2, 'u', 'huevo|huevos', 'lac'],
      [0.75, 'taza', 'leche (la que prefieras)', 'lac'],
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [2, 'taza', 'avena en hojuelas', 'gra'],
      [2, 'u', 'medida de proteína en polvo sabor vainilla (opcional)|medidas de proteína en polvo sabor vainilla (opcional)', 'otr'],
      [1, 'taza', 'zanahoria rallada', 'ver'],
      [0.5, 'taza', 'nueces o pecanas picadas', 'otr'],
      [2, 'cda', 'miel de abejas', 'sal'],
      [1, 'cdta', 'canela en polvo', 'bas'],
      [0.25, 'cdta', 'jengibre en polvo', 'bas'],
      [0.25, 'cdta', 'nuez moscada', 'bas'],
      [1, 'cdta', 'polvo de hornear', 'gra'],
      [null, 'gusto', 'pizca de sal', 'bas'],
      ['Cubierta cremosa'],
      [1, 'taza', 'queso cottage (o requesón)', 'lac'],
      [2, 'cda', 'yogur griego natural sin azúcar', 'lac'],
      [2, 'cda', 'miel de abejas', 'sal'],
      [null, 'gusto', 'un chorrito de vainilla y canela', 'sal'],
    ],
    pasos: [
      'Prende el horno a 175 °C. Engrasa un molde cuadrado de unos 20 cm (8 x 8 pulgadas).',
      'En un tazón grande pisa los bananos con un tenedor. Agrega los huevos, la leche y el yogur, y mezcla.',
      'Agrega la avena, la proteína en polvo, la zanahoria rallada, las nueces, la miel, la canela, el jengibre, la nuez moscada, el polvo de hornear y una pizca de sal. Mezcla hasta que quede todo integrado.',
      'Vierte en el molde y hornea de 30 a 35 minutos.',
      'Cubierta: licúa el queso cottage con el yogur, la miel, un chorrito de vainilla y canela hasta que quede completamente lisa.',
      'Deja enfriar la avena, cúbrela con la crema y corta en 4 porciones. Si quieres, guarda la crema aparte y ponla porción por porción.',
    ],
    liv: 'Media porción (u 8 cuadros del molde, uno por día) con la crema de cottage. Sin proteína en polvo y con menos nueces baja bastante de calorías.',
    mus: 'Una porción completa de las 4: unos 34 g de proteína con la proteína en polvo (cerca de 20 g sin ella). Perfecta de desayuno antes del gimnasio.',
    adel: 'Es ideal para dejar listos varios desayunos: dura 4 o 5 días en la nevera. La crema se puede guardar aparte.',
    con: 'Un café o un vaso de leche. Si no tienes proteína en polvo, déjala por fuera: queda igual de rica, con menos proteína.',
  },

  {
    id: 'brownie-cheesecake-proteico', o: 'fb', vu: 'https://www.facebook.com/share/r/1QSekQhGv4/', de: 'J.Newtrition (receta original de AlleYeZonJe)', ingles: true, foto: 'fotos/brownie-cheesecake.jpg',
    fija: 'Una sola tanda: un molde pequeño de unos 18 cm, para 4 porciones',
    n: 'Cheesecake sobre base de brownie, alto en proteína', e: '🍰',
    m: ['postre', 'desayuno'], p: 'lacteo', a: ['freidora|horno'], t: 55, reposo: '30 minutos en la nevera', d: 'Media', kcal: 220, prot: 35,
    ing: [
      ['Base de brownie'],
      [90, 'g', 'frijol negro enlatado, escurrido y enjuagado', 'otr'],
      [4, 'cda', 'cacao en polvo sin azúcar', 'sal'],
      [1, 'cda', 'stevia granulada', 'sal'],
      [2, 'cda', 'leche de almendras (o leche normal)', 'lac'],
      [2, 'cda', 'sirope de chocolate sin azúcar (opcional)', 'sal'],
      [1, 'u', 'medida de proteína en polvo sabor chocolate|medidas de proteína en polvo sabor chocolate', 'otr'],
      ['Relleno de cheesecake'],
      [600, 'g', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'u', 'huevo|huevos', 'lac'],
      [10, 'g', 'gelatina o pudín instantáneo sin azúcar, en polvo', 'gra'],
      [40, 'g', 'proteína en polvo (vainilla o neutra)', 'otr'],
      [15, 'g', 'stevia granulada', 'sal'],
    ],
    pasos: [
      'Base: enjuaga y escurre los frijoles. Pisa o licúa los frijoles con el cacao, la stevia, la leche de almendras, el sirope de chocolate (si usas) y la proteína en polvo, hasta que quede una masa espesa y lisa, como de brownie.',
      'Forra con papel de hornear un molde pequeño (unos 18 cm) y extiende la base de brownie en el fondo, apretándola con una cuchara.',
      'Relleno: licúa el yogur griego con el huevo, la gelatina en polvo, la proteína en polvo y la stevia, hasta que quede completamente liso.',
      'Vierte el relleno encima de la base.',
      'Cocina en la freidora de aire a 200 °C por 30 minutos. En horno, calcula unos 35 a 40 minutos a 180 °C (el video usa freidora; el tiempo del horno es aproximado: está listo cuando el centro ya no se mueve líquido).',
      'Déjalo enfriar un poco y llévalo a la nevera 30 minutos antes de cortar en 4 porciones.',
    ],
    liv: 'Una porción: ya es liviana (unas 220 calorías con 35 g de proteína). Acompáñala con fresas en vez de más porciones.',
    mus: 'Dos porciones: unos 70 g de proteína. Sirve de postre grande o después del gimnasio.',
    adel: 'Se hace en una hora y dura 4 días en la nevera. Se come frío.',
    con: 'Fresas o frambuesas encima. Necesita proteína en polvo para el relleno: sin ella no queda igual de firme. No se siente el sabor a frijol.',
  },

  {
    id: 'avena-tiramisu', o: 'fb', vu: 'https://www.facebook.com/watch/?v=1581203993549943', ingles: true, foto: 'fotos/avena-tiramisu.jpg',
    n: 'Avena de la noche anterior sabor tiramisú', e: '☕',
    m: ['desayuno', 'postre'], p: 'lacteo', a: [], t: 10, reposo: 'toda la noche en la nevera (mínimo 8 horas)', d: 'Fácil', kcal: 458, prot: 33,
    ing: [
      ['Avena'],
      [2, 'taza', 'avena en hojuelas', 'gra'],
      [6, 'cda', 'cacao en polvo sin azúcar', 'sal'],
      [3, 'cda', 'semillas de chía', 'gra'],
      [2, 'cdta', 'esencia de vainilla', 'sal'],
      [null, 'gusto', 'pizca de sal', 'bas'],
      [6, 'cda', 'café tinto fuerte (o espresso), ya frío', 'sal'],
      [2.5, 'taza', 'leche de almendras entera (o leche normal)', 'lac'],
      [4, 'cda', 'miel de abejas', 'sal'],
      ['Cubierta de yogur con proteína'],
      [3, 'taza', 'yogur griego natural sabor vainilla (o natural con 1 cdta de vainilla)', 'lac'],
      [60, 'g', 'proteína en polvo sabor vainilla', 'otr'],
      [1, 'cda', 'miel de abejas', 'sal'],
      [0.5, 'cdta', 'esencia de vainilla', 'sal'],
      [null, 'gusto', 'un poco más de cacao para espolvorear', 'sal'],
    ],
    pasos: [
      'Prepara el café fuerte y déjalo enfriar por completo.',
      'En un tazón mezcla en seco la avena, el cacao, la chía y una pizca de sal.',
      'Agrega el café frío, la leche de almendras, la miel y la vainilla. Mezcla bien y pasa a un recipiente de vidrio con tapa (o a 4 frascos).',
      'Cubierta: bate el yogur griego con la proteína en polvo, la miel y la vainilla hasta que quede lisa.',
      'Extiende la cubierta sobre la avena y espolvorea cacao por encima, pasándolo por un colador para que quede fino, como un tiramisú.',
      'Tapa y deja en la nevera mínimo 8 horas, mejor toda la noche. Amanece listo.',
    ],
    liv: 'Es una porción de unas 458 calorías: si quieres bajarla, usa media porción de avena y la cubierta solo con yogur (sin miel extra).',
    mus: 'La porción completa: 33 g de proteína y 10 g de fibra, de desayuno antes del gimnasio.',
    adel: 'Se prepara la noche anterior y dura 3 días en la nevera: puedes dejar varios desayunos listos.',
    con: 'No necesita nada más. Si no consigues proteína en polvo, quítala: el yogur griego solo ya aporta proteína.',
  },

  {
    id: 'batido-sandia', o: 'fb', vu: 'https://www.cheffatty.com/recipes/watermelon-milkshake', de: 'Chef Fatty (Charles Kim)', ingles: true,
    n: 'Batido cremoso de sandía y limón', e: '🍉',
    m: ['postre'], p: 'lacteo', a: ['licuadora'], t: 10, reposo: 'congelar la sandía desde la noche anterior', d: 'Fácil', kcal: 230, prot: 5,
    ing: [
      [8, 'taza', 'sandía en cubos, congelada (desde la noche anterior)', 'ver'],
      [5, 'cda', 'leche condensada', 'otr'],
      [0.5, 'taza', 'leche entera (la receta original usa mitad leche, mitad crema de leche)', 'lac'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [null, 'gusto', 'pizca de sal', 'bas'],
    ],
    pasos: [
      'La noche anterior pica la sandía en cubos, sin cáscara, y congélala bien (mejor sobre una bandeja y luego en una bolsa, para que no se pegue).',
      'En la licuadora echa la sandía congelada, la leche condensada, la leche, el jugo del limón y una pizca de sal.',
      'Licúa hasta que quede espeso y liso, como un batido de helado. Si está tan espeso que no se mueve, agrega un chorrito de leche y licúa otra vez.',
      'Sírvelo bien frío en vasos altos. Si quieres, una rodaja de limón en el borde.',
    ],
    liv: 'Cambia la leche condensada por 1 taza de yogur griego natural y 2 cucharadas de stevia o miel: baja a unas 130 calorías y sube la proteína.',
    mus: 'Con 1 taza de yogur griego y 1 medida de proteína en polvo en vez de la leche condensada: unos 25 g de proteína por vaso.',
    adel: 'La sandía se congela con hasta 1 semana de anticipación; el batido se hace al momento.',
    con: 'Sirve de postre o de merienda en un día caluroso.',
  },

  // ───────────── Salsas y aderezos (no pican) ─────────────
  // Cantidades para 4 porciones; una porción son unas 3 o 4 cucharadas.
  {
    id: 'salsa-yogur-ajo', o: 'juan', vq: 'salsa de yogur griego con ajo y limón',
    n: 'Salsa de yogur con ajo y limón', e: '🥣',
    m: ['salsa'], p: 'salsa', a: [], t: 5, d: 'Fácil', kcal: 35, prot: 6,
    ing: [
      [1, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [1, 'cda', 'perejil fresco picado (o cilantro)', 'ver'],
      [null, 'gusto', 'sal y pimienta', 'bas'],
    ],
    pasos: [
      'Ralla o machaca el ajo bien finito.',
      'Mezcla el yogur con el ajo, el jugo del limón, el perejil, sal y pimienta.',
      'Déjala 10 minutos en la nevera para que coja sabor. Dura 4 días tapada.',
    ],
    liv: 'Es de las más livianas: úsala en vez de mayonesa o salsa rosada.',
    con: 'Tenders, pollo a la plancha, papas, ensaladas y tacos.',
  },
  {
    id: 'salsa-ranch', o: 'juan', vq: 'aderezo ranch casero con yogur griego',
    n: 'Ranch casero de yogur', e: '🥗',
    m: ['salsa'], p: 'salsa', a: [], t: 5, d: 'Fácil', kcal: 40, prot: 6,
    ing: [
      [1, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [2, 'cda', 'leche descremada o deslactosada', 'lac'],
      [1, 'cdta', 'ajo en polvo', 'bas'],
      [1, 'cdta', 'cebolla en polvo', 'bas'],
      [1, 'cda', 'perejil seco', 'sal'],
      [0.5, 'cdta', 'eneldo seco (opcional)', 'sal'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [null, 'gusto', 'sal y pimienta', 'bas'],
    ],
    pasos: [
      'Mezcla el yogur con la leche hasta que quede cremoso.',
      'Agrega el ajo y la cebolla en polvo, el perejil, el eneldo, el jugo de medio limón, sal y pimienta.',
      'Prueba y ajusta con más limón o sal. Dura 5 días en la nevera.',
    ],
    liv: 'Un ranch normal tiene unas 140 calorías por porción; este, unas 40.',
    con: 'Ensaladas, burritos, hot pockets, palitos de zanahoria y apio.',
  },
  {
    id: 'salsa-aguacate', o: 'juan', vq: 'salsa cremosa de aguacate y yogur',
    n: 'Salsa cremosa de aguacate', e: '🥑',
    m: ['salsa'], p: 'salsa', a: ['licuadora'], t: 5, d: 'Fácil', kcal: 90, prot: 4,
    ing: [
      [1, 'u', 'aguacate|aguacates', 'ver'],
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [1, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [null, 'gusto', 'cilantro', 'ver'],
      [null, 'gusto', 'sal', 'bas'],
    ],
    pasos: [
      'Licúa el aguacate, el yogur, el jugo del limón, el ajo, un puñado de cilantro, sal y 3 cucharadas de agua.',
      'Si queda muy espesa, agrega agua de a cucharada.',
      'Mejor hacerla el mismo día: con el tiempo se oscurece.',
    ],
    liv: 'Dos cucharadas por plato son suficientes.',
    con: 'Tazones de carne, burritos, tacos, huevos y muffins de huevo.',
  },
  {
    id: 'salsa-big-mac', o: 'juan', vq: 'salsa big mac casera con yogur',
    n: 'Salsa Big Mac liviana', e: '🍔',
    m: ['salsa'], p: 'salsa', a: [], t: 5, d: 'Fácil', kcal: 60, prot: 3,
    ing: [
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [2, 'cda', 'mayonesa light', 'sal'],
      [1, 'cda', 'mostaza (normal)', 'sal'],
      [1, 'cda', 'salsa de tomate', 'sal'],
      [1, 'cda', 'pepinillos encurtidos picados', 'sal'],
      [0.5, 'cdta', 'ajo en polvo', 'bas'],
      [0.5, 'cdta', 'cebolla en polvo', 'bas'],
    ],
    pasos: [
      'Pica los pepinillos bien pequeñitos.',
      'Mezcla todo con un chorrito del vinagre del frasco de pepinillos.',
      'Déjala 10 minutos en la nevera. Dura 5 días.',
    ],
    liv: 'Sin la mayonesa queda todavía más liviana.',
    con: 'Tacos Big Mac, hamburguesas, papas y ensaladas.',
  },
  {
    id: 'salsa-bang-bang', o: 'juan', vq: 'salsa bang bang casera',
    n: 'Salsa Bang Bang suave', e: '🍤',
    m: ['salsa'], p: 'salsa', a: [], t: 5, d: 'Fácil', kcal: 70, prot: 3,
    ing: [
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [2, 'cda', 'mayonesa light', 'sal'],
      [3, 'cda', 'salsa agridulce (la de la comida china)', 'sal'],
      [1, 'cdta', 'miel de abejas', 'sal'],
      [null, 'gusto', 'sal', 'bas'],
    ],
    pasos: [
      'Mezcla el yogur, la mayonesa, la salsa agridulce, la miel y una pizca de sal.',
      'Prueba: si la quieren más dulce, un poquito más de salsa agridulce.',
      'Dura 5 días en la nevera.',
    ],
    liv: 'Usa más yogur y menos mayonesa.',
    con: 'Deditos de pollo, tenders, camarones y tazones de arroz.',
    pica: 'La original lleva sriracha: al que le guste picante, que le ponga una cucharadita a su porción.',
  },
  {
    id: 'salsa-pimenton-asado', o: 'juan', vq: 'salsa de pimentón asado con yogur',
    n: 'Salsa de pimentón asado', e: '🫑',
    m: ['salsa'], p: 'salsa', a: ['licuadora', 'estufa|freidora|horno'], t: 15, d: 'Fácil', kcal: 30, prot: 3,
    ing: [
      [1, 'u', 'pimentón rojo|pimentones rojos', 'ver'],
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'cdta', 'pimentón ahumado (no pica)', 'sal'],
      [1, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [null, 'gusto', 'sal', 'bas'],
    ],
    pasos: [
      'Asa el pimentón entero directo en la llama de la estufa, o en la freidora a 200 °C por 10 a 12 minutos, hasta que la piel se ponga negra.',
      'Mételo en una bolsa 5 minutos, pélalo y quítale las semillas.',
      'Licúalo con el yogur, el pimentón ahumado, el ajo, el jugo del limón y sal.',
      'Dura 5 días en la nevera.',
    ],
    liv: 'Muy liviana: unas 30 calorías por porción.',
    con: 'Tazones de carne, tacos, pollo, huevos y papas.',
    pica: 'La versión original lleva chile chipotle: al que le guste picante, que licúe uno en su porción.',
  },
  {
    id: 'salsa-miel-mostaza', o: 'juan', vq: 'salsa de miel y mostaza casera',
    n: 'Salsa de miel y mostaza', e: '🍯',
    m: ['salsa'], p: 'salsa', a: [], t: 5, d: 'Fácil', kcal: 60, prot: 2,
    ing: [
      [3, 'cda', 'mostaza Dijon (o normal)', 'sal'],
      [2, 'cda', 'miel de abejas', 'sal'],
      [0.25, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [null, 'gusto', 'sal', 'bas'],
    ],
    pasos: [
      'Mezcla la mostaza con la miel.',
      'Agrega el yogur, el jugo de medio limón y una pizca de sal, y revuelve hasta que quede lisa.',
      'Dura 5 días en la nevera.',
    ],
    liv: 'Por la miel, mejor 2 cucharadas por plato.',
    con: 'Tenders, deditos de pollo, muslos, cerdo y ensaladas.',
  },
  {
    id: 'vinagreta-limon', o: 'juan', vq: 'vinagreta de limón y mostaza',
    n: 'Vinagreta de limón y mostaza', e: '🍋',
    m: ['salsa'], p: 'salsa', a: [], t: 5, d: 'Fácil', kcal: 90, prot: 0,
    ing: [
      [3, 'cda', 'aceite de oliva', 'bas'],
      [2, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [1, 'cdta', 'mostaza Dijon (o normal)', 'sal'],
      [1, 'cdta', 'miel de abejas', 'sal'],
      [null, 'gusto', 'sal y pimienta', 'bas'],
    ],
    pasos: [
      'Echa todo en un frasco con tapa: el aceite, el jugo de los limones, la mostaza, la miel, sal y pimienta.',
      'Tápalo y agítalo fuerte hasta que se mezcle.',
      'Dura una semana en la nevera. Agítalo antes de usar.',
    ],
    liv: 'Tiene aceite: una cucharada por plato de ensalada.',
    con: 'Cualquier ensalada, la ensalada de pollo y verduras al vapor.',
  },

  // ───────────── Bebidas: sodas con Bretaña (idea de Juan) ─────────────
  // Base para 4 personas = 8 vasos (unos 2 vasos por persona en el día).
  {
    id: 'soda-sandia', o: 'juan', vq: 'soda de sandía con agua con gas',
    n: 'Soda de sandía y limón', e: '🍉',
    m: ['bebida'], p: 'bebida', a: ['licuadora'], t: 10, d: 'Fácil', kcal: 35, prot: 0,
    ing: [
      [4, 'taza', 'sandía en cubos', 'ver'],
      [2, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [null, 'gusto', 'hojas de hierbabuena', 'ver'],
      [1, 'u', 'botella de Bretaña de 1,5 litros|botellas de Bretaña de 1,5 litros', 'otr'],
      [null, 'gusto', 'hielo', 'bas'],
    ],
    pasos: [
      'Licúa la sandía sin agua y sin azúcar. Si no te gustan los pedacitos, cuélala.',
      'Mézclala con el jugo de los limones. Esa es la base: guárdala en un frasco tapado en la nevera (dura 2 días).',
      'Para cada vaso: hielo, un tercio de base y dos tercios de Bretaña bien fría. Revuelve suave para que no se le vaya el gas.',
      'Decora con hojas de hierbabuena.',
    ],
    liv: 'Unas 35 calorías por vaso. Una gaseosa normal tiene unas 150.',
    adel: 'Haz la base dos veces por semana. La Bretaña, bien tapada y en la nevera para que no pierda el gas.',
    con: 'El almuerzo y la comida. Rinde unos 2 vasos por persona.',
  },
  {
    id: 'soda-maracuya', o: 'juan', vq: 'soda de maracuyá con agua con gas',
    n: 'Soda de maracuyá', e: '🥭',
    m: ['bebida'], p: 'bebida', a: ['licuadora'], t: 10, d: 'Fácil', kcal: 25, prot: 0,
    ing: [
      [4, 'u', 'maracuyá|maracuyás', 'ver'],
      [null, 'gusto', 'stevia o endulzante sin azúcar', 'sal'],
      [1, 'u', 'botella de Bretaña de 1,5 litros|botellas de Bretaña de 1,5 litros', 'otr'],
      [null, 'gusto', 'hielo', 'bas'],
    ],
    pasos: [
      'Saca la pulpa de los maracuyás y licúala con 1 taza de agua, con pulsos cortos (prender y apagar) para no romper las semillas.',
      'Cuélala y endulza con un poquito de stevia: el maracuyá es muy ácido. Esa es la base: dura 3 días en la nevera en frasco tapado.',
      'Para cada vaso: hielo, un tercio de base y dos tercios de Bretaña bien fría. Revuelve suave.',
    ],
    liv: 'Con stevia queda en unas 25 calorías por vaso. Con azúcar ya no ayuda a bajar de peso.',
    adel: 'La base dura 3 días en la nevera.',
    con: 'El almuerzo y la comida. Rinde unos 2 vasos por persona.',
  },
  {
    id: 'soda-limon-hierbabuena', o: 'juan', vq: 'soda de limón y hierbabuena',
    n: 'Soda de limón y hierbabuena', e: '🍋',
    m: ['bebida'], p: 'bebida', a: ['licuadora'], t: 10, d: 'Fácil', kcal: 10, prot: 0,
    ing: [
      [5, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [1, 'u', 'manojo de hierbabuena|manojos de hierbabuena', 'ver'],
      [null, 'gusto', 'stevia o endulzante sin azúcar', 'sal'],
      [1, 'u', 'botella de Bretaña de 1,5 litros|botellas de Bretaña de 1,5 litros', 'otr'],
      [null, 'gusto', 'hielo', 'bas'],
    ],
    pasos: [
      'Licúa el jugo de los limones con la hierbabuena (sin los tallos gruesos) y 1 taza de agua, 20 segundos.',
      'Cuélala y endulza con un poquito de stevia. Esa es la base: dura 2 días en la nevera.',
      'Para cada vaso: hielo, un tercio de base y dos tercios de Bretaña bien fría. Agrega unas hojitas de hierbabuena.',
    ],
    liv: 'Casi no tiene calorías: unas 10 por vaso.',
    adel: 'La base dura 2 días en la nevera.',
    con: 'El almuerzo y la comida. Rinde unos 2 vasos por persona.',
  },
  {
    id: 'soda-fresa', o: 'juan', vq: 'soda de fresa con agua con gas',
    n: 'Soda de fresa', e: '🍓',
    m: ['bebida'], p: 'bebida', a: ['licuadora'], t: 10, d: 'Fácil', kcal: 20, prot: 0,
    ing: [
      [2, 'taza', 'fresas (frescas o congeladas)', 'ver'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [null, 'gusto', 'stevia o endulzante sin azúcar', 'sal'],
      [1, 'u', 'botella de Bretaña de 1,5 litros|botellas de Bretaña de 1,5 litros', 'otr'],
      [null, 'gusto', 'hielo', 'bas'],
    ],
    pasos: [
      'Licúa las fresas con el jugo del limón y media taza de agua.',
      'Cuélala si no te gustan las semillitas y endulza solo si hace falta. Esa es la base: dura 2 días en la nevera.',
      'Para cada vaso: hielo, un tercio de base y dos tercios de Bretaña bien fría. Revuelve suave.',
    ],
    liv: 'Unas 20 calorías por vaso.',
    adel: 'Con fresas congeladas sale más barata y siempre hay.',
    con: 'El almuerzo y la comida. Rinde unos 2 vasos por persona.',
  },
  {
    id: 'soda-lulo', o: 'juan', vq: 'soda de lulo con agua con gas',
    n: 'Soda de lulo', e: '🍊',
    m: ['bebida'], p: 'bebida', a: ['licuadora'], t: 10, d: 'Fácil', kcal: 20, prot: 0,
    ing: [
      [4, 'u', 'lulo|lulos', 'ver'],
      [null, 'gusto', 'stevia o endulzante sin azúcar', 'sal'],
      [1, 'u', 'botella de Bretaña de 1,5 litros|botellas de Bretaña de 1,5 litros', 'otr'],
      [null, 'gusto', 'hielo', 'bas'],
    ],
    pasos: [
      'Parte los lulos por la mitad y saca la pulpa con una cuchara.',
      'Licúa la pulpa con 1 taza de agua, con pulsos cortos. Cuélala y endulza con un poquito de stevia. Esa es la base: dura 2 días en la nevera.',
      'Para cada vaso: hielo, un tercio de base y dos tercios de Bretaña bien fría. Revuelve suave.',
    ],
    liv: 'Unas 20 calorías por vaso.',
    adel: 'La base dura 2 días en la nevera.',
    con: 'El almuerzo y la comida. Rinde unos 2 vasos por persona.',
  },
  {
    id: 'soda-pepino-jengibre', o: 'juan', vq: 'soda de pepino limón y jengibre',
    n: 'Soda de pepino, limón y jengibre', e: '🥒',
    m: ['bebida'], p: 'bebida', a: ['licuadora'], t: 10, d: 'Fácil', kcal: 10, prot: 0,
    ing: [
      [1, 'u', 'pepino cohombro|pepinos cohombros', 'ver'],
      [3, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [1, 'u', 'trocito de jengibre (como un dedo)|trocitos de jengibre (como un dedo)', 'ver'],
      [null, 'gusto', 'hojas de hierbabuena', 'ver'],
      [1, 'u', 'botella de Bretaña de 1,5 litros|botellas de Bretaña de 1,5 litros', 'otr'],
      [null, 'gusto', 'hielo', 'bas'],
    ],
    pasos: [
      'Licúa el pepino con cáscara, el jugo de los limones, el jengibre pelado y 1 taza de agua.',
      'Cuélala. Esa es la base: dura 2 días en la nevera.',
      'Para cada vaso: hielo, un tercio de base y dos tercios de Bretaña bien fría, con hojas de hierbabuena.',
    ],
    liv: 'La más liviana de todas: unas 10 calorías por vaso.',
    adel: 'La base dura 2 días en la nevera.',
    con: 'El almuerzo y la comida. Rinde unos 2 vasos por persona.',
  },
  {
    id: 'soda-pina', o: 'juan', vq: 'soda de piña y hierbabuena',
    n: 'Soda de piña y hierbabuena', e: '🍍',
    m: ['bebida'], p: 'bebida', a: ['licuadora'], t: 10, d: 'Fácil', kcal: 40, prot: 0,
    ing: [
      [2, 'taza', 'piña en cubos', 'ver'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [null, 'gusto', 'hojas de hierbabuena', 'ver'],
      [1, 'u', 'botella de Bretaña de 1,5 litros|botellas de Bretaña de 1,5 litros', 'otr'],
      [null, 'gusto', 'hielo', 'bas'],
    ],
    pasos: [
      'Licúa la piña con el jugo del limón, unas hojas de hierbabuena y media taza de agua.',
      'Cuélala. La piña ya es dulce: no necesita azúcar. Esa es la base: dura 2 días en la nevera.',
      'Para cada vaso: hielo, un tercio de base y dos tercios de Bretaña bien fría. Revuelve suave.',
    ],
    liv: 'Unas 40 calorías por vaso, sin nada de azúcar.',
    adel: 'La base dura 2 días en la nevera.',
    con: 'El almuerzo y la comida. Rinde unos 2 vasos por persona.',
  },
];

// Platos de la casa: tu mamá ya los sabe hacer, así que aquí solo van como ideas
// ("¿Por qué no hoy un ajiaco?"). Sin ingredientes ni pasos.
const IDEAS_CASA = [
  { id: 'casa-pericos', n: 'Huevos pericos con arepa', art: 'unos huevos pericos con arepa', e: '🍳', m: ['desayuno'], p: 'huevo' },
  { id: 'casa-calentado', n: 'Calentado', art: 'un calentado', e: '🍛', m: ['desayuno'], p: 'granos' },
  { id: 'casa-arepa-huevo', n: 'Arepa con quesito y huevo', art: 'una arepa con quesito y huevo', e: '🫓', m: ['desayuno'], p: 'huevo' },
  { id: 'casa-avena', n: 'Avena licuada con banano', art: 'una avena licuada con banano', e: '🥤', m: ['desayuno'], p: 'lacteo' },
  { id: 'casa-omelette', n: 'Omelette con verduras', art: 'un omelette con verduras', e: '🍳', m: ['desayuno', 'comida'], p: 'huevo' },
  { id: 'casa-tostadas', n: 'Tostadas con aguacate y huevo', art: 'unas tostadas con aguacate y huevo', e: '🥑', m: ['desayuno'], p: 'huevo' },
  { id: 'casa-yogur', n: 'Yogur griego con fruta y granola', art: 'un yogur con fruta y granola', e: '🍓', m: ['desayuno'], p: 'lacteo' },
  { id: 'casa-frijoles', n: 'Frijoles', art: 'unos frijoles', e: '🫘', m: ['almuerzo'], p: 'granos' },
  { id: 'casa-sancocho', n: 'Sancocho', art: 'un sancocho', e: '🍲', m: ['almuerzo'], p: 'pollo' },
  { id: 'casa-ajiaco', n: 'Ajiaco', art: 'un ajiaco', e: '🍲', m: ['almuerzo'], p: 'pollo' },
  { id: 'casa-arroz-pollo', n: 'Arroz con pollo', art: 'un arroz con pollo', e: '🍚', m: ['almuerzo', 'comida'], p: 'pollo' },
  { id: 'casa-sudado', n: 'Sudado de pollo con papa', art: 'un sudado de pollo', e: '🍲', m: ['almuerzo', 'comida'], p: 'pollo' },
  { id: 'casa-bistec', n: 'Carne en bistec', art: 'una carne en bistec', e: '🥩', m: ['almuerzo', 'comida'], p: 'res' },
  { id: 'casa-lentejas', n: 'Lentejas', art: 'unas lentejas', e: '🥣', m: ['almuerzo', 'comida'], p: 'granos' },
  { id: 'casa-pescado', n: 'Pescado con patacones', art: 'un pescado con patacones', e: '🐟', m: ['almuerzo', 'comida'], p: 'pescado' },
  { id: 'casa-albondigas', n: 'Albóndigas en salsa', art: 'unas albóndigas en salsa', e: '🍝', m: ['almuerzo', 'comida'], p: 'res' },
  { id: 'casa-desmechada', n: 'Carne desmechada', art: 'una carne desmechada', e: '🥩', m: ['almuerzo', 'comida'], p: 'res' },
  { id: 'casa-higado', n: 'Hígado encebollado', art: 'un hígado encebollado', e: '🥘', m: ['almuerzo', 'comida'], p: 'res' },
  { id: 'casa-cerdo', n: 'Lomito de cerdo a la plancha', art: 'un lomito de cerdo a la plancha', e: '🐖', m: ['almuerzo', 'comida'], p: 'cerdo' },
  { id: 'casa-atun', n: 'Ensalada de atún', art: 'una ensalada de atún', e: '🐟', m: ['almuerzo', 'comida'], p: 'pescado' },
  { id: 'casa-crema', n: 'Crema de ahuyama con pollo', art: 'una crema de ahuyama con pollo', e: '🎃', m: ['comida'], p: 'pollo' },
  { id: 'casa-sopa', n: 'Sopa de verduras', art: 'una sopita de verduras', e: '🥣', m: ['comida'], p: 'vegetal' },
];
