// Recetas de la casa. Cantidades para 4 porciones (la app las ajusta a las personas).
//
// ing: [cantidad, unidad, nombre, pasillo]  ó  ['Subtítulo']
//   unidad:  g | taza | cda | cdta | u (unidades) | gusto
//   nombre:  "singular|plural" cuando cambia con la cantidad
//   pasillo: car carnes/pollo/pescado · ver frutas y verduras · lac huevos y lácteos
//            gra arroz, granos y harinas · pan arepas, pan y tortillas · sal salsas y especias
//            otr enlatados y otros · bas básicos de la cocina · sob sobrado de otro día
// a: aparatos que necesita. "freidora|horno" = sirve cualquiera de los dos.
// o: 'h4s' = inspirada en @hunt4shredz (video en inglés) · 'col' = clásica colombiana
// kcal / prot: aproximados por porción, sin acompañantes.

const RECETAS = [
  // ───────────── Inspiradas en @hunt4shredz ─────────────
  {
    id: 'tenders-miel-picante', o: 'h4s', v: '9GesJYk6gQY',
    n: 'Tenders de pollo con limón, pimienta y miel picante', e: '🍗',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['freidora|horno'], t: 30, d: 'Fácil', kcal: 430, prot: 45,
    ing: [
      [800, 'g', 'filetes de pechuga de pollo (o pechuga en tiras)', 'car'],
      [0.5, 'taza', 'harina de trigo', 'gra'],
      [2, 'u', 'huevo|huevos', 'lac'],
      [3, 'taza', 'Corn Flakes sin azúcar', 'gra'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [1, 'cdta', 'pimienta negra molida', 'bas'],
      [1, 'cdta', 'ajo en polvo', 'bas'],
      [1, 'cdta', 'sal', 'bas'],
      [null, 'gusto', 'aceite en spray', 'bas'],
      ['Salsa de miel picante'],
      [3, 'cda', 'miel de abejas', 'sal'],
      [1, 'cda', 'salsa picante', 'sal'],
      [1, 'cdta', 'mantequilla (opcional)', 'lac'],
    ],
    pasos: [
      'Ralla la cáscara del limón (solo lo verde) y mézclala con la pimienta, el ajo en polvo y la sal. Úntale la mitad al pollo.',
      'Arma 3 platos: uno con la harina, otro con los huevos batidos y otro con los Corn Flakes triturados con la mano.',
      'Pasa cada tira de pollo por harina, luego por huevo y luego por Corn Flakes, apretando bien para que se pegue.',
      'Rocía con aceite en spray. Freidora de aire a 200 °C por 10 a 12 minutos, volteando a la mitad. En horno: 220 °C por 18 a 20 minutos.',
      'Salsa: calienta la miel con la salsa picante (y la mantequilla si quieres) en una ollita a fuego bajo 1 minuto. Rocíala sobre los tenders y espolvorea el resto del condimento de limón.',
    ],
    liv: 'Sirve 4 o 5 tenders con una ensalada grande en vez de papas, y solo 1 cucharadita de la salsa de miel.',
    adel: 'Se pueden apanar el día anterior y guardar crudos en la nevera, o congelarlos ya apanados.',
    con: 'Ensalada fresca o papa criolla en la freidora.',
  },
  {
    id: 'burritos-cajun', o: 'h4s', v: 'cYrEJoqG8bA',
    n: 'Burritos de pollo cajún con arroz', e: '🌯',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['estufa'], t: 35, d: 'Fácil', kcal: 600, prot: 46,
    ing: [
      [700, 'g', 'muslos de pollo sin hueso ni piel (o pechuga)', 'car'],
      [1, 'u', 'cebolla cabezona|cebollas cabezonas', 'ver'],
      [1, 'u', 'pimentón rojo|pimentones rojos', 'ver'],
      [1, 'u', 'pimentón verde|pimentones verdes', 'ver'],
      [2, 'cda', 'condimento cajún (o pimentón en polvo + ajo + orégano + una pizca de cayena)', 'sal'],
      [1, 'taza', 'arroz blanco (crudo)', 'gra'],
      [8, 'u', 'tortilla de trigo integral|tortillas de trigo integrales', 'pan'],
      ['Salsa cajún cremosa'],
      [1, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'cdta', 'perejil seco', 'sal'],
      [1, 'cdta', 'ajo en polvo', 'bas'],
    ],
    pasos: [
      'Cocina el arroz como siempre.',
      'Corta el pollo en cubitos, y la cebolla y los pimentones en tiras.',
      'En una sartén grande con un chorrito de aceite, dora el pollo con casi todo el condimento cajún, 6 a 8 minutos. Agrega la cebolla y los pimentones y cocina 5 minutos más.',
      'Mezcla el arroz con el pollo en la sartén.',
      'Salsa: revuelve el yogur con el perejil, el ajo en polvo, una pizca de sal y el resto del condimento cajún.',
      'Rellena cada tortilla con la mezcla y un poco de salsa, enróllala y dórala en la sartén seca 1 minuto por cada lado para que cierre.',
    ],
    liv: 'Un burrito en vez de dos, con ensalada. O sirve el relleno en un plato sin tortilla.',
    adel: 'El relleno dura 4 días en la nevera. Los burritos armados se congelan envueltos en papel aluminio.',
    con: 'Guacamole en licuadora.',
  },
  {
    id: 'pollo-3-marinadas', o: 'h4s', v: 'BxncjnpLT-I',
    n: 'Pollo con 3 marinadas (limón, mostaza-miel y soya-jengibre)', e: '🍋',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['horno|freidora'], t: 40, d: 'Fácil', kcal: 340, prot: 45,
    ing: [
      [900, 'g', 'pechuga de pollo sin hueso', 'car'],
      ['Marinada 1: limón y hierbas'],
      [2, 'cda', 'aceite de oliva', 'bas'],
      [2, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [1, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'romero y tomillo (frescos o secos)', 'sal'],
      [1, 'cdta', 'mostaza Dijon (o normal)', 'sal'],
      ['Marinada 2: mostaza y miel picante'],
      [1, 'cda', 'mostaza Dijon (o normal)', 'sal'],
      [1, 'cda', 'miel de abejas', 'sal'],
      [1, 'cda', 'vinagre de manzana', 'sal'],
      [1, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [0.5, 'cdta', 'pimentón en polvo (paprika)', 'sal'],
      [null, 'gusto', 'pizca de cayena o ají en polvo', 'sal'],
      ['Marinada 3: soya y jengibre'],
      [2, 'cda', 'salsa soya baja en sodio', 'sal'],
      [1, 'cda', 'miel de abejas', 'sal'],
      [1, 'cda', 'vinagre de manzana', 'sal'],
      [1, 'cdta', 'jengibre fresco rallado', 'ver'],
      [1, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'aceite de ajonjolí (opcional)', 'sal'],
      [1, 'cdta', 'sriracha (opcional)', 'sal'],
    ],
    pasos: [
      'Divide el pollo en 3 bolsas con cierre (o 3 recipientes con tapa).',
      'Marinada 1: aceite, jugo de los limones, ajo picado, romero, tomillo, mostaza, sal y pimienta.',
      'Marinada 2: mostaza, miel, vinagre, ajo picado, pimentón, una pizca de cayena y sal.',
      'Marinada 3: soya, miel, vinagre, jengibre, ajo picado, aceite de ajonjolí y sriracha.',
      'Echa cada marinada en su bolsa, masajea y deja en la nevera mínimo 30 minutos (mejor toda la noche).',
      'Horno a 200 °C por 25 minutos, o freidora de aire a 190 °C por 15 a 18 minutos, volteando a la mitad. Corta el más grueso: no debe quedar rosado por dentro.',
    ],
    liv: 'Perfecta para bajar de peso: acompaña con verduras y media taza de arroz o una papa pequeña.',
    adel: 'Ideal para el domingo: marina las 3 bolsas y congélalas. La noche anterior pasa una a la nevera.',
    con: 'Arroz, ensalada o verduras al vapor.',
  },
  {
    id: 'burritos-desayuno', o: 'h4s', v: 'ghwbWfca5gM',
    n: 'Burritos de desayuno con carne y huevo', e: '🌯',
    m: ['desayuno'], p: 'res', a: ['estufa', 'freidora|horno'], t: 35, d: 'Media', kcal: 600, prot: 40,
    ing: [
      [2, 'u', 'papa pastusa mediana|papas pastusas medianas', 'ver'],
      [0.5, 'u', 'cebolla cabezona|cebollas cabezonas', 'ver'],
      [450, 'g', 'carne molida de res magra', 'car'],
      [2, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'comino', 'bas'],
      [1, 'cdta', 'pimentón en polvo (paprika)', 'sal'],
      [1, 'cda', 'salsa inglesa', 'sal'],
      [6, 'u', 'huevo|huevos', 'lac'],
      [4, 'u', 'tortilla de trigo grande|tortillas de trigo grandes', 'pan'],
      [1, 'u', 'tallo de cebolla larga|tallos de cebolla larga', 'ver'],
      [60, 'g', 'queso mozzarella rallado', 'lac'],
      ['Salsa de aguacate'],
      [1, 'u', 'aguacate|aguacates', 'ver'],
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
    ],
    pasos: [
      'Papas en cubitos con un chorrito de aceite y sal: freidora de aire a 200 °C por 15 minutos, moviéndolas a la mitad (o horno a 220 °C por 25 minutos).',
      'En una sartén, sofríe la cebolla picada, agrega la carne y el ajo y cocina hasta que dore. Sazona con comino, pimentón, salsa inglesa, sal y pimienta.',
      'Aparte, revuelve los huevos con sal a fuego bajo.',
      'Salsa: pisa el aguacate con el yogur, el jugo del limón y sal.',
      'Arma: tortilla + papas + carne + huevo + queso + cebolla larga picada. Enrolla y dora en la sartén 1 minuto por cada lado.',
    ],
    liv: 'Medio burrito con una fruta, o el relleno en plato sin tortilla.',
    adel: 'Se congelan envueltos en papel aluminio hasta por 1 mes. Se calientan sin el aluminio en la freidora a 180 °C por 8 a 10 minutos.',
    con: 'Café o chocolate sin azúcar y una fruta.',
  },
  {
    id: 'deditos-bang-bang', o: 'h4s', v: 'Y0buYRLicag',
    n: 'Deditos de pollo Bang Bang', e: '🍤',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['freidora|horno'], t: 30, d: 'Fácil', kcal: 440, prot: 46,
    ing: [
      [800, 'g', 'filetes de pechuga de pollo (o pechuga en tiras)', 'car'],
      [0.5, 'taza', 'harina de trigo', 'gra'],
      [2, 'u', 'huevo|huevos', 'lac'],
      [3, 'taza', 'Corn Flakes sin azúcar', 'gra'],
      [1, 'cdta', 'ajo en polvo', 'bas'],
      [1, 'cdta', 'cebolla en polvo', 'bas'],
      [1, 'cdta', 'sal', 'bas'],
      [null, 'gusto', 'aceite en spray', 'bas'],
      ['Salsa Bang Bang'],
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [2, 'cda', 'mayonesa light', 'sal'],
      [3, 'cda', 'salsa de chile dulce (sweet chili)', 'sal'],
      [1, 'cdta', 'sriracha (o salsa picante)', 'sal'],
      [1, 'cdta', 'miel de abejas', 'sal'],
    ],
    pasos: [
      'Sazona el pollo con sal, pimienta, ajo en polvo y cebolla en polvo.',
      'Arma 3 platos: harina, huevos batidos y Corn Flakes triturados con la mano.',
      'Pasa cada tira por harina, huevo y Corn Flakes, apretando bien.',
      'Rocía con aceite en spray. Freidora de aire a 200 °C por 10 a 12 minutos, volteando a la mitad (horno: 220 °C por 18 a 20 minutos).',
      'Salsa: mezcla el yogur, la mayonesa, la salsa de chile dulce, la sriracha, la miel y una pizca de sal. Sirve los deditos con la salsa para untar.',
    ],
    liv: 'En la salsa usa más yogur y nada de mayonesa. Acompaña con ensalada de pepino.',
    adel: 'La salsa dura 5 días en la nevera. El pollo se puede apanar el día anterior.',
    con: 'Ensalada de pepino y tomate, o arroz.',
  },
  {
    id: 'muffins-huevo-papa', o: 'h4s', v: 'BCLq_5_1hpc',
    n: 'Muffins de huevo con base de papa crujiente', e: '🧁',
    m: ['desayuno'], p: 'huevo', a: ['horno'], t: 40, d: 'Media', kcal: 310, prot: 22,
    ing: [
      [2, 'u', 'papa pastusa mediana|papas pastusas medianas', 'ver'],
      [10, 'u', 'huevo|huevos', 'lac'],
      [0.5, 'u', 'pimentón rojo|pimentones rojos', 'ver'],
      [1, 'u', 'tallo de cebolla larga|tallos de cebolla larga', 'ver'],
      [1, 'taza', 'espinaca picada', 'ver'],
      [60, 'g', 'jamón (de pavo o de cerdo)', 'car'],
      [60, 'g', 'queso mozzarella rallado', 'lac'],
      [null, 'gusto', 'aceite en spray', 'bas'],
    ],
    pasos: [
      'Prende el horno a 190 °C y engrasa un molde para 12 muffins (los moldes de silicona también sirven).',
      'Ralla las papas, exprímelas con un trapo limpio para sacarles el agua y sazónalas con sal y un chorrito de aceite.',
      'Pon una capa de papa en el fondo de cada molde, apretando con una cuchara. Hornea 15 minutos hasta que dore: esa es la base crujiente.',
      'Bate los huevos con sal y pimienta. Agrega el pimentón, la cebolla larga, la espinaca, el jamón picado y el queso.',
      'Reparte la mezcla sobre las bases de papa y hornea 18 a 20 minutos más, hasta que el huevo esté firme.',
    ],
    liv: 'Dos muffins con una fruta es un desayuno de unas 300 calorías.',
    adel: 'Duran 4 días en la nevera. Se calientan 5 minutos en la freidora de aire a 170 °C.',
    con: 'Una fruta y café.',
  },
  {
    id: 'muslos-glaseados', o: 'h4s', vq: 'hunt4shredz smoked chicken thighs glaze',
    n: 'Muslos de pollo ahumados con glaseado de miel', e: '🍗',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['horno|freidora'], t: 45, d: 'Fácil', kcal: 470, prot: 40,
    ing: [
      [8, 'u', 'muslo de pollo|muslos de pollo', 'car'],
      [1, 'cda', 'pimentón ahumado (o pimentón normal)', 'sal'],
      [1, 'cdta', 'ajo en polvo', 'bas'],
      [1, 'cdta', 'cebolla en polvo', 'bas'],
      [1, 'cda', 'panela rallada', 'gra'],
      [1, 'cdta', 'sal', 'bas'],
      ['Glaseado'],
      [3, 'cda', 'miel de abejas', 'sal'],
      [2, 'cda', 'salsa BBQ', 'sal'],
      [1, 'cda', 'vinagre de manzana', 'sal'],
      [1, 'cdta', 'salsa picante (opcional)', 'sal'],
    ],
    pasos: [
      'Mezcla el pimentón ahumado, el ajo, la cebolla en polvo, la panela, la sal y pimienta. Unta bien los muslos por todos lados.',
      'Horno a 200 °C por 35 a 40 minutos, o freidora de aire a 190 °C por 22 a 25 minutos, volteando a la mitad.',
      'Mientras tanto mezcla la miel, la salsa BBQ, el vinagre y la salsa picante.',
      'Los últimos 5 minutos, pinta los muslos con el glaseado y termina de cocinar hasta que brillen.',
      'Revisa que el jugo del pollo salga transparente al pincharlo cerca del hueso.',
    ],
    liv: 'Quítales la piel antes de cocinarlos y come un muslo con ensalada y media taza de arroz.',
    adel: 'Adoba los muslos la noche anterior y guárdalos tapados en la nevera.',
    con: 'Papa criolla, arroz o ensalada de repollo.',
  },
  {
    id: 'tacos-big-mac', o: 'h4s', v: '-8xJgVk5iUs',
    n: 'Tacos Big Mac (carne en tortilla tostada)', e: '🌮',
    m: ['almuerzo', 'comida'], p: 'res', a: ['estufa'], t: 25, d: 'Fácil', kcal: 540, prot: 38,
    ing: [
      [500, 'g', 'carne molida de res magra', 'car'],
      [8, 'u', 'tortilla de trigo pequeña|tortillas de trigo pequeñas', 'pan'],
      [4, 'u', 'tajada de queso amarillo|tajadas de queso amarillo', 'lac'],
      [2, 'taza', 'lechuga picada', 'ver'],
      [0.5, 'u', 'cebolla cabezona|cebollas cabezonas', 'ver'],
      [4, 'u', 'pepinillo encurtido|pepinillos encurtidos', 'sal'],
      ['Salsa Big Mac'],
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [2, 'cda', 'mayonesa light', 'sal'],
      [1, 'cda', 'mostaza (normal)', 'sal'],
      [1, 'cda', 'salsa de tomate', 'sal'],
      [0.5, 'cdta', 'ajo en polvo', 'bas'],
      [0.5, 'cdta', 'cebolla en polvo', 'bas'],
    ],
    pasos: [
      'Salsa: mezcla el yogur, la mayonesa, la mostaza, la salsa de tomate, 1 cucharada de pepinillos picados, un chorrito del vinagre del frasco de pepinillos, el ajo y la cebolla en polvo.',
      'Divide la carne en 8 bolitas. Aplasta cada bolita sobre una tortilla, en una capa delgada hasta el borde. Ponle sal y pimienta.',
      'Pon la tortilla en la sartén bien caliente con la carne hacia abajo, 3 a 4 minutos hasta que dore. Voltéala, pon media tajada de queso y deja 1 minuto más.',
      'Sirve con lechuga, cebolla picada, pepinillos y salsa. Dobla como un taco.',
    ],
    liv: 'Dos tacos con una ensalada grande, y la salsa solo con yogur (sin mayonesa).',
    adel: 'La salsa se puede hacer el día anterior y dura 5 días en la nevera.',
    con: 'Ensalada de lechuga y tomate.',
  },
  {
    id: 'pollo-mexicano-olla', o: 'h4s', v: 'xhwV8mYQoro',
    n: 'Pollo mexicano en olla lenta', e: '🌶️',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['olla'], t: 15, lento: '4 h en ALTO o 6 a 8 h en BAJO', d: 'Fácil', kcal: 420, prot: 55,
    ing: [
      [1000, 'g', 'pechuga de pollo sin hueso', 'car'],
      [1, 'taza', 'salsa para tacos (frasco) o 3 tomates licuados con ½ cebolla', 'sal'],
      [1, 'u', 'lata de frijoles rojos o negros (400 g)|latas de frijoles rojos o negros (400 g)', 'otr'],
      [1, 'taza', 'maíz tierno desgranado', 'otr'],
      [1, 'cda', 'comino', 'bas'],
      [1, 'cda', 'pimentón en polvo (paprika)', 'sal'],
      [1, 'cdta', 'ajo en polvo', 'bas'],
      [1, 'cdta', 'orégano seco', 'sal'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [null, 'gusto', 'cilantro', 'ver'],
    ],
    pasos: [
      'Pon las pechugas en la olla lenta (descongeladas, nunca congeladas). Sazona con comino, pimentón, ajo, orégano y sal.',
      'Echa encima la salsa, los frijoles escurridos y el maíz.',
      'Tapa y cocina 4 horas en ALTO o 6 a 8 horas en BAJO. No destapes mientras se cocina.',
      'Desmecha el pollo con dos tenedores dentro de la olla y revuelve todo.',
      'Termina con el jugo del limón y cilantro picado. Sirve en tazón con arroz, en tacos o con arepa.',
    ],
    liv: 'Sírvelo sobre lechuga picada en vez de arroz.',
    adel: 'Rinde para dos comidas y dura 4 días en la nevera. También se congela.',
    con: 'Arroz, arepa o guacamole.',
  },
  {
    id: 'tazon-pollo-pegajoso', o: 'h4s', v: 'WvvWT8krk7o',
    n: 'Tazón de pollo pegajoso con batata', e: '🍠',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['estufa', 'freidora|horno'], t: 35, d: 'Fácil', kcal: 450, prot: 47,
    ing: [
      [800, 'g', 'pechuga de pollo sin hueso', 'car'],
      [2, 'u', 'batata mediana|batatas medianas', 'ver'],
      [1, 'cdta', 'pimentón en polvo (paprika)', 'sal'],
      [2, 'taza', 'brócoli en arbolitos', 'ver'],
      ['Salsa pegajosa'],
      [3, 'cda', 'salsa soya baja en sodio', 'sal'],
      [3, 'cda', 'miel de abejas', 'sal'],
      [2, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'jengibre fresco rallado', 'ver'],
      [1, 'cdta', 'sriracha (opcional)', 'sal'],
      [1, 'cdta', 'fécula de maíz (Maizena)', 'gra'],
      [1, 'u', 'tallo de cebolla larga|tallos de cebolla larga', 'ver'],
      [null, 'gusto', 'ajonjolí (opcional)', 'sal'],
    ],
    pasos: [
      'Pela la batata y córtala en cubos. Mézclala con un chorrito de aceite, sal y pimentón. Freidora de aire a 200 °C por 18 a 20 minutos (horno: 220 °C por 25 minutos).',
      'Corta el pollo en cubos y dóralo en una sartén con poco aceite, 6 a 8 minutos.',
      'Mezcla la soya, la miel, el ajo picado, el jengibre, la sriracha y la Maizena disuelta en 2 cucharadas de agua. Échala al pollo y deja 2 minutos hasta que espese y brille.',
      'Cocina el brócoli al vapor o en agua hirviendo 4 a 5 minutos.',
      'Sirve en tazón: batata, pollo pegajoso, brócoli, cebolla larga picada y ajonjolí.',
    ],
    liv: 'Media batata, doble brócoli y solo 1 cucharada de miel en la salsa.',
    adel: 'La batata y el pollo se pueden dejar listos para 3 días. La salsa se agrega al calentar.',
    con: 'Ya es plato completo.',
  },
  {
    id: 'tenders-limon-pimienta', o: 'h4s', v: 'jdXtavlNgDk',
    n: 'Tenders de pollo al limón y pimienta con salsa de yogur', e: '🍋',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['freidora|horno'], t: 30, d: 'Fácil', kcal: 380, prot: 48,
    ing: [
      [800, 'g', 'filetes de pechuga de pollo (o pechuga en tiras)', 'car'],
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [2, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [1, 'taza', 'miga de pan o apanadura', 'gra'],
      [2, 'cdta', 'pimienta negra molida', 'bas'],
      [1, 'cdta', 'ajo en polvo', 'bas'],
      [1, 'cdta', 'sal', 'bas'],
      [null, 'gusto', 'aceite en spray', 'bas'],
      ['Salsa de yogur'],
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'cda', 'perejil fresco picado', 'ver'],
      [1, 'u', 'diente de ajo|dientes de ajo', 'ver'],
    ],
    pasos: [
      'Mezcla media taza de yogur con el jugo de un limón, la ralladura de los dos limones, sal y pimienta. Unta el pollo y deja 15 minutos (o toda la noche en la nevera).',
      'En un plato mezcla la miga de pan con el resto de la pimienta, el ajo en polvo y una pizca de sal.',
      'Saca cada tira del yogur y pásala por la miga de pan, apretando bien.',
      'Rocía con aceite en spray. Freidora de aire a 200 °C por 10 a 12 minutos, volteando a la mitad (horno: 220 °C por 18 minutos).',
      'Salsa: mezcla el otro medio de yogur con el jugo del segundo limón, el perejil, el ajo bien picadito y sal.',
    ],
    liv: 'Con ensalada grande y la salsa de yogur: es de las recetas más livianas.',
    adel: 'Deja el pollo marinando en yogur desde la noche anterior: queda más jugoso.',
    con: 'Ensalada o papa criolla.',
  },
  {
    id: 'tazon-carne-criolla', o: 'h4s', v: 'l13R0L1FQBA',
    n: 'Tazón de carne con papa criolla y salsa de aguacate', e: '🥑',
    m: ['almuerzo', 'comida'], p: 'res', a: ['estufa', 'freidora|horno', 'licuadora'], t: 35, d: 'Fácil', kcal: 475, prot: 32,
    ing: [
      [500, 'g', 'carne molida de res magra', 'car'],
      [600, 'g', 'papa criolla', 'ver'],
      [0.5, 'u', 'cebolla cabezona|cebollas cabezonas', 'ver'],
      [2, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'comino', 'bas'],
      [1, 'cdta', 'pimentón en polvo (paprika)', 'sal'],
      [2, 'u', 'tomate chonto|tomates chontos', 'ver'],
      [2, 'taza', 'lechuga picada', 'ver'],
      ['Salsa de aguacate (licuadora)'],
      [1, 'u', 'aguacate|aguacates', 'ver'],
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [null, 'gusto', 'cilantro', 'ver'],
    ],
    pasos: [
      'Parte las papas criollas por la mitad, échales un chorrito de aceite y sal. Freidora de aire a 200 °C por 18 a 20 minutos, moviéndolas a la mitad.',
      'En una sartén sofríe la cebolla picada y el ajo, agrega la carne y cocina hasta que dore. Sazona con comino, pimentón, sal y pimienta.',
      'Salsa: licúa el aguacate, el yogur, el jugo del limón, un puñado de cilantro, sal y 2 o 3 cucharadas de agua hasta que quede cremosa.',
      'Arma el tazón: lechuga, papas, carne, tomate picado y la salsa por encima.',
    ],
    liv: 'De 6 a 8 papitas por plato y doble lechuga.',
    adel: 'La carne y las papas duran 4 días en la nevera. La salsa, mejor el mismo día (se oscurece).',
    con: 'Ya es plato completo.',
  },
  {
    id: 'tacos-pollo-chipotle', o: 'h4s', v: 'ArWKo3-vJqs',
    n: 'Tacos de pollo desmechado con salsa chipotle', e: '🌮',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['estufa', 'licuadora'], t: 40, d: 'Fácil', kcal: 370, prot: 44,
    ing: [
      [700, 'g', 'pechuga de pollo sin hueso', 'car'],
      [1, 'u', 'cebolla cabezona|cebollas cabezonas', 'ver'],
      [2, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'comino', 'bas'],
      [1, 'cdta', 'pimentón en polvo (paprika)', 'sal'],
      [8, 'u', 'tortilla pequeña de maíz o trigo|tortillas pequeñas de maíz o trigo', 'pan'],
      [1, 'taza', 'repollo morado picado', 'ver'],
      [null, 'gusto', 'cilantro', 'ver'],
      ['Salsa chipotle (licuadora)'],
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'u', 'chile chipotle en adobo (lata) o 1 cdta de pimentón ahumado|chiles chipotle en adobo (lata)', 'sal'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
    ],
    pasos: [
      'Cocina el pollo en agua con media cebolla, el ajo y sal por 20 minutos. Sácalo y desméchalo con dos tenedores.',
      'En una sartén con poco aceite, saltea el pollo desmechado con comino, pimentón y un chorrito del caldo, 3 minutos.',
      'Salsa: licúa el yogur, el chipotle (empieza con uno: pica), el jugo del limón y sal.',
      'Calienta las tortillas en la sartén seca.',
      'Arma: tortilla, pollo, repollo, cebolla picada, cilantro y salsa.',
    ],
    liv: 'Dos tacos con bastante repollo, en tortilla de maíz.',
    adel: 'El pollo desmechado dura 4 días en la nevera. Guarda el caldo para sopas o arroz.',
    con: 'Guacamole en licuadora.',
  },
  {
    id: 'tazon-carne-chipotle', o: 'h4s', vq: 'hunt4shredz high protein beef potato bowl',
    n: 'Tazón de carne con papa y salsa chipotle de pimentón rojo', e: '🌶️',
    m: ['almuerzo', 'comida'], p: 'res', a: ['estufa', 'freidora|horno', 'licuadora'], t: 40, d: 'Media', kcal: 440, prot: 31,
    ing: [
      [500, 'g', 'carne molida de res magra', 'car'],
      [3, 'u', 'papa pastusa mediana|papas pastusas medianas', 'ver'],
      [1, 'cdta', 'comino', 'bas'],
      [1, 'cdta', 'ajo en polvo', 'bas'],
      [1, 'taza', 'maíz tierno desgranado', 'otr'],
      [2, 'taza', 'lechuga picada', 'ver'],
      [0.5, 'u', 'cebolla morada|cebollas moradas', 'ver'],
      ['Salsa de pimentón asado (licuadora)'],
      [1, 'u', 'pimentón rojo|pimentones rojos', 'ver'],
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'u', 'chile chipotle en adobo (lata) o 1 cdta de pimentón ahumado|chiles chipotle en adobo (lata)', 'sal'],
      [1, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
    ],
    pasos: [
      'Papas en cubos con un chorrito de aceite y sal: freidora de aire a 200 °C por 18 a 20 minutos (horno: 220 °C por 25 a 30 minutos).',
      'Asa el pimentón entero en la freidora (200 °C, 10 a 12 minutos) o directo en la llama de la estufa, hasta que la piel se ponga negra. Mételo en una bolsa 5 minutos y pélalo.',
      'Salsa: licúa el pimentón asado (sin semillas), el yogur, el chipotle, el ajo, el jugo del limón y sal.',
      'Dora la carne en una sartén con comino, ajo en polvo, sal y pimienta. Agrega el maíz al final.',
      'Arma el tazón: lechuga, papas, carne con maíz, cebolla morada picada y la salsa por encima.',
    ],
    liv: 'Una papa pequeña por plato y más lechuga.',
    adel: 'La salsa dura 5 días en la nevera. La carne y la papa, 4 días.',
    con: 'Ya es plato completo.',
  },
  {
    id: 'guacamole-licuadora', o: 'h4s', v: 'TWGTu8SRY2I',
    n: 'Guacamole en licuadora', e: '🥑',
    m: ['acompañante'], p: 'vegetal', a: ['licuadora'], t: 10, d: 'Fácil', kcal: 180, prot: 2,
    ing: [
      [3, 'u', 'aguacate|aguacates', 'ver'],
      [2, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [0.25, 'u', 'cebolla morada|cebollas moradas', 'ver'],
      [1, 'u', 'tomate chonto|tomates chontos', 'ver'],
      [1, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [null, 'gusto', 'cilantro', 'ver'],
      [null, 'gusto', 'ají o jalapeño (opcional)', 'ver'],
    ],
    pasos: [
      'Licúa primero el jugo de los limones, la cebolla, el ajo, el cilantro, el ají y sal.',
      'Agrega la pulpa de los aguacates y licúa con pulsos cortos (prender y apagar) para que quede con textura, no como puré.',
      'Pásalo a un tazón y agrega el tomate picado en cubitos.',
      'Tápalo con plástico pegado al guacamole para que no se ponga negro.',
    ],
    liv: 'Dos cucharadas por plato son suficientes: es sano pero tiene muchas calorías.',
    adel: 'Mejor hacerlo el mismo día.',
    con: 'Tacos, burritos, carne desmechada o pollo mexicano.',
  },
  {
    id: 'ensalada-pollo-proteina', o: 'h4s', vq: 'hunt4shredz high protein chicken salad',
    n: 'Ensalada de pollo alta en proteína', e: '🥗',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['estufa'], t: 30, d: 'Fácil', kcal: 260, prot: 40,
    ing: [
      [600, 'g', 'pechuga de pollo sin hueso', 'car'],
      [1, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'cda', 'mostaza (normal)', 'sal'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [2, 'u', 'tallo de apio|tallos de apio', 'ver'],
      [1, 'u', 'manzana verde|manzanas verdes', 'ver'],
      [0.25, 'u', 'cebolla morada|cebollas moradas', 'ver'],
      [null, 'gusto', 'perejil fresco picado', 'ver'],
      [4, 'u', 'hoja grande de lechuga|hojas grandes de lechuga', 'ver'],
    ],
    pasos: [
      'Cocina el pollo en agua con sal, un diente de ajo y un pedazo de cebolla por 20 minutos. Déjalo enfriar y córtalo en cubitos o desméchalo.',
      'Pica el apio, la manzana (con cáscara) y la cebolla morada bien pequeñitos.',
      'Mezcla el yogur con la mostaza, el jugo del limón, sal y pimienta.',
      'Revuelve el pollo, las verduras, la manzana y la salsa. Agrega perejil.',
      'Déjala en la nevera 20 minutos y sírvela sobre hojas de lechuga, en pan integral o con arepa.',
    ],
    liv: 'Sobre hojas de lechuga, sin pan ni arepa.',
    adel: 'Dura 3 días en la nevera. Puedes usar pollo que sobró de otra receta.',
    con: 'Pan integral, arepa o galletas integrales.',
  },
  {
    id: 'hot-pockets-buffalo', o: 'h4s', vq: 'hunt4shredz buffalo chicken hot pocket',
    n: 'Hot pockets de pollo buffalo', e: '🥟',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['freidora|horno'], t: 30, d: 'Media', kcal: 435, prot: 43,
    ing: [
      [500, 'g', 'pechuga de pollo sin hueso', 'car'],
      [3, 'cda', 'salsa buffalo (tipo Frank\'s RedHot) o salsa picante con 1 cdta de mantequilla', 'sal'],
      [0.25, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'cdta', 'ajo en polvo', 'bas'],
      [80, 'g', 'queso mozzarella rallado', 'lac'],
      [4, 'u', 'tortilla de trigo grande|tortillas de trigo grandes', 'pan'],
      [1, 'u', 'huevo|huevos', 'lac'],
      [1, 'u', 'tallo de cebolla larga|tallos de cebolla larga', 'ver'],
    ],
    pasos: [
      'Cocina el pollo en agua con sal 20 minutos y desméchalo (o usa pollo que haya sobrado).',
      'Mezcla el pollo con la salsa buffalo, el yogur, el ajo en polvo, el queso y la cebolla larga picada.',
      'Pon una porción en el centro de cada tortilla. Dobla los 4 lados hacia el centro, como un sobre, y voltéalo con el doblez hacia abajo.',
      'Píntalos con huevo batido. Freidora de aire a 190 °C por 6 a 8 minutos hasta que doren (horno: 200 °C por 12 a 15 minutos).',
    ],
    liv: 'Un hot pocket con palitos de apio y zanahoria.',
    adel: 'Se arman el día anterior y se guardan crudos en la nevera, o se congelan.',
    con: 'Palitos de apio y zanahoria con salsa de yogur.',
  },

  // ───────────── Clásicas colombianas — desayunos ─────────────
  {
    id: 'pericos-arepa', o: 'col',
    n: 'Huevos pericos con arepa y queso', e: '🍳',
    m: ['desayuno'], p: 'huevo', a: ['estufa'], t: 15, d: 'Fácil', kcal: 425, prot: 20,
    ing: [
      [8, 'u', 'huevo|huevos', 'lac'],
      [2, 'u', 'tomate chonto|tomates chontos', 'ver'],
      [2, 'u', 'tallo de cebolla larga|tallos de cebolla larga', 'ver'],
      [4, 'u', 'arepa blanca|arepas blancas', 'pan'],
      [120, 'g', 'queso campesino', 'lac'],
      [1, 'cdta', 'sal', 'bas'],
    ],
    pasos: [
      'Pica el tomate y la cebolla larga bien pequeñitos.',
      'Sofríelos en una sartén con poquito aceite, 3 a 4 minutos.',
      'Bate los huevos con sal, échalos a la sartén y revuelve a fuego bajo hasta que cuajen pero queden jugosos.',
      'Asa las arepas en la sartén o en la parrilla hasta que doren.',
      'Sirve los pericos con la arepa y un pedazo de queso.',
    ],
    liv: 'Arepa delgada (tipo tela) y dos huevos por persona.',
    adel: 'Deja el tomate y la cebolla picados la noche anterior.',
    con: 'Chocolate o café con leche y una fruta.',
  },
  {
    id: 'calentado-paisa', o: 'col',
    n: 'Calentado paisa', e: '🍛',
    m: ['desayuno'], p: 'granos', a: ['estufa'], t: 15, d: 'Fácil', kcal: 420, prot: 17,
    ing: [
      [2, 'taza', 'frijoles cocidos (de la olla de frijoles)', 'sob'],
      [2, 'taza', 'arroz cocido (del día anterior)', 'sob'],
      [1, 'u', 'tomate chonto|tomates chontos', 'ver'],
      [1, 'u', 'tallo de cebolla larga|tallos de cebolla larga', 'ver'],
      [4, 'u', 'huevo|huevos', 'lac'],
      [2, 'u', 'arepa blanca|arepas blancas', 'pan'],
    ],
    pasos: [
      'Pica el tomate y la cebolla larga y sofríelos en una sartén con poquito aceite, 3 minutos.',
      'Agrega los frijoles y el arroz, y revuelve hasta que todo esté bien caliente, unos 5 minutos.',
      'Aparte, fríe los huevos con poquito aceite (o hazlos pericos).',
      'Sirve el calentado con el huevo encima y media arepa.',
    ],
    liv: 'Media taza de calentado, un huevo y nada de arepa.',
    adel: 'Es para usar lo que sobró de los frijoles y el arroz.',
    con: 'Chocolate o café y aguacate.',
  },
  {
    id: 'avena-licuada', o: 'col',
    n: 'Avena licuada con banano y canela', e: '🥤',
    m: ['desayuno'], p: 'lacteo', a: ['licuadora'], t: 10, d: 'Fácil', kcal: 240, prot: 14,
    ing: [
      [1, 'taza', 'avena en hojuelas', 'gra'],
      [4, 'taza', 'leche descremada o deslactosada', 'lac'],
      [2, 'u', 'banano|bananos', 'ver'],
      [0.5, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [1, 'cdta', 'canela en polvo', 'bas'],
      [null, 'gusto', 'miel o stevia (opcional)', 'sal'],
    ],
    pasos: [
      'Remoja la avena en la leche 5 minutos (o déjala así en la nevera desde la noche anterior).',
      'Licúa la avena con la leche, los bananos, el yogur y la canela.',
      'Prueba y endulza solo si hace falta. Sirve bien fría.',
    ],
    liv: 'Sin miel, y un banano para toda la licuada.',
    adel: 'Deja la avena remojando en la nevera la noche anterior: queda más cremosa.',
    con: 'Un huevo cocido si quieres más proteína.',
  },
  {
    id: 'omelette-espinaca', o: 'col',
    n: 'Omelette de espinaca, tomate y queso', e: '🍳',
    m: ['desayuno', 'comida'], p: 'huevo', a: ['estufa'], t: 15, d: 'Fácil', kcal: 250, prot: 17,
    ing: [
      [8, 'u', 'huevo|huevos', 'lac'],
      [2, 'taza', 'espinaca picada', 'ver'],
      [1, 'u', 'tomate chonto|tomates chontos', 'ver'],
      [1, 'u', 'tallo de cebolla larga|tallos de cebolla larga', 'ver'],
      [80, 'g', 'queso campesino', 'lac'],
      [1, 'cdta', 'sal', 'bas'],
    ],
    pasos: [
      'Pica la espinaca, el tomate y la cebolla larga. Desmenuza el queso.',
      'Sofríe la cebolla y el tomate 2 minutos en una sartén pequeña con poquito aceite. Agrega la espinaca hasta que se marchite.',
      'Bate 2 huevos por persona con sal. Échalos sobre las verduras y cocina a fuego bajo con tapa, 3 a 4 minutos.',
      'Pon el queso en una mitad, dobla el omelette y sírvelo. Repite para cada persona.',
    ],
    liv: 'Usa 1 huevo entero y 2 claras por persona.',
    adel: 'Deja las verduras picadas en un recipiente la noche anterior.',
    con: 'Arepa delgada o pan integral y una fruta.',
  },
  {
    id: 'tostadas-aguacate', o: 'col',
    n: 'Tostadas de aguacate con huevo', e: '🥑',
    m: ['desayuno'], p: 'huevo', a: ['estufa'], t: 15, d: 'Fácil', kcal: 355, prot: 15,
    ing: [
      [8, 'u', 'tajada de pan integral|tajadas de pan integral', 'pan'],
      [2, 'u', 'aguacate|aguacates', 'ver'],
      [4, 'u', 'huevo|huevos', 'lac'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [null, 'gusto', 'ají en hojuelas (opcional)', 'sal'],
    ],
    pasos: [
      'Tuesta el pan en una sartén seca o en la freidora (180 °C, 3 minutos).',
      'Pisa el aguacate con un tenedor, con el jugo del limón, sal y pimienta.',
      'Fríe los huevos con poquito aceite, o cocínalos en agua hirviendo (pochados) 3 minutos.',
      'Unta el aguacate en el pan y pon el huevo encima. Si quieres, un toque de ají.',
    ],
    liv: 'Una tostada con aguacate y huevo, más una fruta.',
    adel: 'Nada: se hace en el momento.',
    con: 'Café o chocolate y fruta.',
  },
  {
    id: 'yogur-fruta-granola', o: 'col',
    n: 'Yogur griego con fruta y granola', e: '🍓',
    m: ['desayuno'], p: 'lacteo', a: [], t: 5, d: 'Fácil', kcal: 320, prot: 18,
    ing: [
      [3, 'taza', 'yogur griego natural sin azúcar', 'lac'],
      [2, 'taza', 'fruta picada (fresa, banano, papaya o mango)', 'ver'],
      [1, 'taza', 'granola', 'gra'],
      [2, 'cda', 'miel de abejas (opcional)', 'sal'],
    ],
    pasos: [
      'Pica la fruta.',
      'En cada vaso o tazón pon yogur, fruta y una cucharada grande de granola.',
      'Si quieres, un hilito de miel por encima.',
    ],
    liv: 'Media porción de granola y sin miel.',
    adel: 'La fruta se puede dejar picada la noche anterior (menos el banano).',
    con: 'Un café.',
  },

  // ───────────── Clásicas colombianas — almuerzos y comidas ─────────────
  {
    id: 'frijoles-olla-lenta', o: 'col',
    n: 'Frijoles antioqueños en olla lenta', e: '🫘',
    m: ['almuerzo'], p: 'granos', a: ['olla', 'estufa'], t: 30, lento: '8 h en BAJO o 5 h en ALTO', d: 'Media', kcal: 520, prot: 30,
    ing: [
      [400, 'g', 'frijol cargamanto (remojado desde la noche anterior)', 'gra'],
      [300, 'g', 'costilla de cerdo (opcional)', 'car'],
      [1, 'u', 'plátano verde|plátanos verdes', 'ver'],
      [1, 'u', 'zanahoria|zanahorias', 'ver'],
      ['Hogao'],
      [2, 'u', 'tomate chonto|tomates chontos', 'ver'],
      [2, 'u', 'tallo de cebolla larga|tallos de cebolla larga', 'ver'],
      [2, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'comino', 'bas'],
      [1, 'cdta', 'color (achiote)', 'bas'],
      [1, 'cdta', 'sal', 'bas'],
    ],
    pasos: [
      'La noche anterior: lava los frijoles y déjalos en remojo con bastante agua.',
      'Muy importante: bota el agua del remojo y hierve los frijoles en una olla en la estufa, a fuego fuerte, 10 minutos. La olla lenta sola no calienta lo suficiente para que el frijol crudo sea seguro.',
      'Pasa los frijoles a la olla lenta con agua que los cubra unos 5 dedos, la costilla, la zanahoria rallada y el plátano verde en trocitos.',
      'Tapa y cocina 8 horas en BAJO o 5 horas en ALTO, hasta que estén blanditos.',
      'Hogao: sofríe en una sartén el tomate y la cebolla picados, el ajo, el comino y el color, 8 a 10 minutos.',
      'Echa el hogao a la olla la última media hora y ponle la sal al final (si se pone al principio, el frijol queda duro).',
    ],
    liv: 'Una taza de frijoles, media de arroz y ensalada. Sin costilla.',
    adel: 'Rinden para 2 o 3 días y se congelan muy bien en porciones. Lo que sobre sirve para el calentado.',
    con: 'Arroz, aguacate, tajada de maduro y carne molida.',
  },
  {
    id: 'sancocho-pollo', o: 'col',
    n: 'Sancocho de pollo', e: '🍲',
    m: ['almuerzo'], p: 'pollo', a: ['estufa'], t: 70, d: 'Media', kcal: 520, prot: 36,
    ing: [
      [1000, 'g', 'presas de pollo (pernil o pierna)', 'car'],
      [3, 'u', 'papa pastusa mediana|papas pastusas medianas', 'ver'],
      [300, 'g', 'yuca', 'ver'],
      [1, 'u', 'plátano verde|plátanos verdes', 'ver'],
      [2, 'u', 'mazorca|mazorcas', 'ver'],
      [2, 'u', 'tallo de cebolla larga|tallos de cebolla larga', 'ver'],
      [3, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'comino', 'bas'],
      [1, 'cdta', 'color (achiote)', 'bas'],
      [null, 'gusto', 'cilantro', 'ver'],
      [null, 'gusto', 'sal', 'bas'],
    ],
    pasos: [
      'En una olla grande pon el pollo con agua que lo cubra bien (unos 3 litros para 4 personas), la cebolla larga entera, el ajo machacado, el comino, el color y sal. Hierve 20 minutos.',
      'Agrega el plátano verde en trozos (pártelo con la mano para que suelte almidón) y la mazorca en ruedas. Cocina 15 minutos.',
      'Agrega la yuca en trozos y cocina 15 minutos más.',
      'Agrega las papas en trozos y cocina 15 a 20 minutos, hasta que todo esté blandito.',
      'Saca la cebolla larga, prueba la sal y termina con bastante cilantro picado.',
    ],
    liv: 'Mucho caldo y pollo, poca yuca y papa, y sin arroz.',
    adel: 'Pela y corta las verduras el día anterior; deja la yuca y la papa en agua en la nevera.',
    con: 'Arroz, aguacate y limón.',
  },
  {
    id: 'ajiaco', o: 'col',
    n: 'Ajiaco', e: '🍲',
    m: ['almuerzo'], p: 'pollo', a: ['estufa'], t: 75, d: 'Media', kcal: 580, prot: 45,
    ing: [
      [1000, 'g', 'pechuga de pollo con hueso', 'car'],
      [500, 'g', 'papa criolla', 'ver'],
      [500, 'g', 'papa pastusa', 'ver'],
      [500, 'g', 'papa sabanera', 'ver'],
      [2, 'u', 'mazorca|mazorcas', 'ver'],
      [2, 'u', 'tallo de cebolla larga|tallos de cebolla larga', 'ver'],
      [3, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [2, 'cda', 'guascas secas', 'sal'],
      [0.5, 'taza', 'crema de leche', 'lac'],
      [2, 'cda', 'alcaparras', 'sal'],
      [1, 'u', 'aguacate|aguacates', 'ver'],
      [null, 'gusto', 'sal', 'bas'],
    ],
    pasos: [
      'Hierve la pechuga en agua que la cubra bien (unos 3 litros para 4 personas) con la cebolla larga, el ajo y sal, 25 minutos. Saca el pollo y desméchalo. Deja el caldo.',
      'Pela las papas. Corta la sabanera y la pastusa en rodajas y échalas al caldo con las mazorcas en trozos. Cocina 20 minutos.',
      'Agrega la papa criolla entera y las guascas, y cocina 20 minutos más, revolviendo de vez en cuando: la papa criolla se deshace y espesa la sopa.',
      'Vuelve a echar el pollo desmechado y prueba la sal.',
      'Sirve con crema de leche, alcaparras y aguacate al lado, para que cada uno se sirva.',
    ],
    liv: 'Sin crema (o una cucharadita) y medio plato de papa.',
    adel: 'El pollo se puede cocinar y desmechar el día anterior. Guarda el caldo.',
    con: 'Arroz y aguacate.',
  },
  {
    id: 'arroz-con-pollo', o: 'col',
    n: 'Arroz con pollo', e: '🍚',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['estufa'], t: 50, d: 'Media', kcal: 580, prot: 42,
    ing: [
      [600, 'g', 'pechuga de pollo sin hueso', 'car'],
      [2, 'taza', 'arroz blanco (crudo)', 'gra'],
      [1, 'u', 'zanahoria|zanahorias', 'ver'],
      [1, 'u', 'pimentón rojo|pimentones rojos', 'ver'],
      [1, 'taza', 'arveja verde desgranada', 'ver'],
      [1, 'u', 'cebolla cabezona|cebollas cabezonas', 'ver'],
      [2, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'color (achiote)', 'bas'],
      [1, 'cda', 'salsa inglesa', 'sal'],
      [null, 'gusto', 'cilantro', 'ver'],
      [null, 'gusto', 'sal', 'bas'],
    ],
    pasos: [
      'Cocina el pollo en 5 tazas de agua con sal y un pedazo de cebolla, 20 minutos. Sácalo y desméchalo. Guarda 4 tazas de ese caldo.',
      'En una olla con un chorrito de aceite sofríe la cebolla, el ajo, el pimentón y la zanahoria picados, 5 minutos.',
      'Agrega el arroz y el color y revuelve 1 minuto.',
      'Echa las 4 tazas de caldo, la salsa inglesa y sal. Cuando hierva, agrega el pollo y la arveja.',
      'Cuando se seque el agua de encima, tapa y deja a fuego bajo 18 a 20 minutos. Termina con cilantro.',
    ],
    liv: 'Media taza de arroz con pollo y una ensalada grande al lado.',
    adel: 'El pollo cocido y desmechado se puede dejar listo el día anterior.',
    con: 'Ensalada, aguacate y tajadas de maduro.',
  },
  {
    id: 'sudado-pollo', o: 'col',
    n: 'Sudado de pollo con papa', e: '🍲',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['estufa|olla'], t: 45, d: 'Fácil', kcal: 470, prot: 42,
    ing: [
      [1000, 'g', 'presas de pollo sin piel', 'car'],
      [4, 'u', 'papa pastusa mediana|papas pastusas medianas', 'ver'],
      [3, 'u', 'tomate chonto|tomates chontos', 'ver'],
      [1, 'u', 'cebolla cabezona|cebollas cabezonas', 'ver'],
      [2, 'u', 'tallo de cebolla larga|tallos de cebolla larga', 'ver'],
      [3, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'comino', 'bas'],
      [1, 'cdta', 'color (achiote)', 'bas'],
      [null, 'gusto', 'cilantro', 'ver'],
      [null, 'gusto', 'sal', 'bas'],
    ],
    pasos: [
      'Adoba el pollo con ajo machacado, comino, color, sal y pimienta.',
      'En una olla con un chorrito de aceite, sofríe la cebolla cabezona, la cebolla larga y el tomate picados, 5 minutos (eso es el hogao).',
      'Agrega el pollo y revuelve para que se impregne. Agrega las papas en mitades y media taza de agua.',
      'Tapa y cocina a fuego bajo 30 a 35 minutos, hasta que la papa esté blanda. En olla lenta: todo junto 6 horas en BAJO.',
      'Termina con cilantro picado.',
    ],
    liv: 'Pollo sin piel, una papa por persona y ensalada.',
    adel: 'Deja el pollo adobado desde la noche anterior.',
    con: 'Arroz blanco y aguacate.',
  },
  {
    id: 'carne-en-bistec', o: 'col',
    n: 'Carne en bistec', e: '🥩',
    m: ['almuerzo', 'comida'], p: 'res', a: ['estufa'], t: 40, d: 'Fácil', kcal: 370, prot: 45,
    ing: [
      [700, 'g', 'carne de res para bistec (bola o cadera)', 'car'],
      [3, 'u', 'tomate chonto|tomates chontos', 'ver'],
      [2, 'u', 'cebolla cabezona|cebollas cabezonas', 'ver'],
      [3, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'comino', 'bas'],
      [1, 'cda', 'salsa inglesa', 'sal'],
      [null, 'gusto', 'sal', 'bas'],
    ],
    pasos: [
      'Adoba la carne con ajo machacado, comino, salsa inglesa, sal y pimienta. Deja 20 minutos.',
      'Dórala en una sartén caliente con poquito aceite, 2 minutos por lado. Sácala.',
      'En la misma sartén pon la cebolla en aros y el tomate en tajadas, 5 minutos.',
      'Devuelve la carne, agrega media taza de agua, tapa y cocina a fuego bajo 20 a 25 minutos hasta que esté blandita.',
    ],
    liv: 'Con ensalada y una papa cocida, en vez de arroz y papa.',
    adel: 'Deja la carne adobada desde la noche anterior: queda más blanda.',
    con: 'Arroz, papa cocida y ensalada.',
  },
  {
    id: 'lentejas', o: 'col',
    n: 'Lentejas con verduras', e: '🥣',
    m: ['almuerzo', 'comida'], p: 'granos', a: ['estufa'], t: 45, d: 'Fácil', kcal: 445, prot: 26,
    ing: [
      [400, 'g', 'lentejas', 'gra'],
      [2, 'u', 'papa pastusa mediana|papas pastusas medianas', 'ver'],
      [1, 'u', 'zanahoria|zanahorias', 'ver'],
      [2, 'u', 'tomate chonto|tomates chontos', 'ver'],
      [2, 'u', 'tallo de cebolla larga|tallos de cebolla larga', 'ver'],
      [2, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'comino', 'bas'],
      [1, 'cdta', 'color (achiote)', 'bas'],
      [1, 'u', 'chorizo (opcional)|chorizos (opcional)', 'car'],
      [null, 'gusto', 'cilantro', 'ver'],
      [null, 'gusto', 'sal', 'bas'],
    ],
    pasos: [
      'Lava las lentejas y quita las piedritas (no necesitan remojo).',
      'Hogao: sofríe el tomate, la cebolla larga y el ajo picados con el comino y el color, 5 minutos. Si usas chorizo, dóralo aquí en rodajas.',
      'Agrega las lentejas y agua que las cubra unos 3 dedos (6 tazas para 4 personas). Cocina 20 minutos.',
      'Agrega la papa y la zanahoria en cubos y cocina 15 minutos más, hasta que todo esté blando.',
      'Ponle la sal al final y termina con cilantro.',
    ],
    liv: 'Sin chorizo, taza y media de lentejas con ensalada: ya traen su proteína.',
    adel: 'Duran 4 días en la nevera y se congelan bien.',
    con: 'Arroz, aguacate y tajada de maduro.',
  },
  {
    id: 'tilapia-patacones', o: 'col',
    n: 'Tilapia en freidora de aire con patacones', e: '🐟',
    m: ['almuerzo', 'comida'], p: 'pescado', a: ['freidora'], t: 35, d: 'Media', kcal: 320, prot: 31,
    ing: [
      [4, 'u', 'filete de tilapia (o mojarra pequeña)|filetes de tilapia (o mojarras pequeñas)', 'car'],
      [2, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [2, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'pimentón en polvo (paprika)', 'sal'],
      [2, 'u', 'plátano verde|plátanos verdes', 'ver'],
      [null, 'gusto', 'aceite en spray', 'bas'],
      [null, 'gusto', 'sal', 'bas'],
      ['Ensalada'],
      [2, 'u', 'tomate chonto|tomates chontos', 'ver'],
      [0.5, 'u', 'cebolla morada|cebollas moradas', 'ver'],
    ],
    pasos: [
      'Adoba el pescado con el jugo de un limón, ajo machacado, pimentón y sal. Deja 10 minutos.',
      'Patacones: pela los plátanos y córtalos en trozos de 3 dedos. Rocía con aceite y cocina en la freidora a 190 °C por 10 minutos.',
      'Aplástalos con la pataconera o con el fondo de un vaso, rocía otra vez, ponles sal y cocina 8 a 10 minutos más hasta que doren. Resérvalos.',
      'Pescado: rocía con aceite y cocina en la freidora a 200 °C por 10 a 12 minutos los filetes (la mojarra entera, 18 a 20 minutos, volteándola a la mitad).',
      'Ensalada: tomate y cebolla morada picados con limón y sal.',
    ],
    liv: 'Dos patacones por persona y bastante ensalada.',
    adel: 'Los patacones se pueden dejar aplastados (crudos) desde la mañana.',
    con: 'Arroz con coco o ensalada.',
  },
  {
    id: 'albondigas', o: 'col',
    n: 'Albóndigas en salsa de tomate', e: '🍝',
    m: ['almuerzo', 'comida'], p: 'res', a: ['estufa'], t: 45, d: 'Media', kcal: 360, prot: 33,
    ing: [
      [600, 'g', 'carne molida de res magra', 'car'],
      [1, 'u', 'huevo|huevos', 'lac'],
      [0.5, 'taza', 'avena en hojuelas', 'gra'],
      [4, 'u', 'tomate chonto|tomates chontos', 'ver'],
      [1, 'u', 'cebolla cabezona|cebollas cabezonas', 'ver'],
      [3, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'comino', 'bas'],
      [1, 'cdta', 'orégano seco', 'sal'],
      [null, 'gusto', 'cilantro', 'ver'],
      [null, 'gusto', 'sal', 'bas'],
    ],
    pasos: [
      'Mezcla la carne con el huevo, la avena, la mitad de la cebolla rallada, un diente de ajo, comino, sal y pimienta. Forma bolitas del tamaño de un limón.',
      'Dóralas en una sartén con poquito aceite por todos lados. Sácalas.',
      'Licúa los tomates con el resto de la cebolla y el ajo. Echa la salsa en la sartén con el orégano y sal, y cocina 5 minutos.',
      'Pon las albóndigas en la salsa, tapa y cocina a fuego bajo 15 a 20 minutos. Termina con cilantro.',
    ],
    liv: 'Con verduras al vapor o ahuyama, en vez de pasta o arroz.',
    adel: 'Las albóndigas crudas se pueden armar y congelar.',
    con: 'Arroz, pasta o puré de papa.',
  },
  {
    id: 'carne-desmechada-olla', o: 'col',
    n: 'Carne desmechada en olla lenta', e: '🥩',
    m: ['almuerzo', 'comida'], p: 'res', a: ['olla', 'estufa'], t: 25, lento: '8 h en BAJO o 5 h en ALTO', d: 'Fácil', kcal: 360, prot: 40,
    ing: [
      [800, 'g', 'falda de res', 'car'],
      [1, 'u', 'cebolla cabezona|cebollas cabezonas', 'ver'],
      [3, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [3, 'u', 'tomate chonto|tomates chontos', 'ver'],
      [1, 'u', 'pimentón rojo|pimentones rojos', 'ver'],
      [2, 'u', 'tallo de cebolla larga|tallos de cebolla larga', 'ver'],
      [1, 'cdta', 'comino', 'bas'],
      [1, 'cdta', 'color (achiote)', 'bas'],
      [null, 'gusto', 'sal', 'bas'],
    ],
    pasos: [
      'Pon la falda en la olla lenta con media cebolla, el ajo, sal y media taza de agua.',
      'Tapa y cocina 8 horas en BAJO o 5 horas en ALTO, hasta que se deshaga con un tenedor.',
      'Saca la carne y desméchala con dos tenedores. Guarda el caldo.',
      'Hogao: en una sartén sofríe el tomate, la cebolla larga, el resto de la cebolla y el pimentón picados con comino y color, 8 minutos.',
      'Mezcla la carne con el hogao y un poco del caldo, y cocina 10 minutos a fuego bajo.',
    ],
    liv: 'Con ensalada y una arepa delgada.',
    adel: 'Rinde para dos comidas y se congela muy bien.',
    con: 'Arroz, arepa, patacón o aguacate.',
  },
  {
    id: 'crema-ahuyama', o: 'col',
    n: 'Crema de ahuyama', e: '🎃',
    m: ['comida'], p: 'vegetal', a: ['estufa', 'licuadora'], t: 35, d: 'Fácil', kcal: 170, prot: 5,
    ing: [
      [1000, 'g', 'ahuyama', 'ver'],
      [1, 'u', 'papa pastusa mediana|papas pastusas medianas', 'ver'],
      [1, 'u', 'cebolla cabezona|cebollas cabezonas', 'ver'],
      [2, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [4, 'taza', 'caldo de pollo (o agua con un cubito)', 'bas'],
      [0.5, 'taza', 'leche descremada o deslactosada', 'lac'],
      [null, 'gusto', 'sal', 'bas'],
    ],
    pasos: [
      'Sofríe la cebolla y el ajo picados en una olla con un chorrito de aceite, 3 minutos.',
      'Agrega la ahuyama pelada en cubos, la papa en cubos y el caldo. Cocina 20 minutos hasta que todo esté blando.',
      'Licúa por partes con cuidado: no llenes la licuadora más de la mitad, deja la tapa un poquito abierta y ponle un trapo encima (el vapor empuja).',
      'Devuelve a la olla, agrega la leche, sal y pimienta, y calienta sin que hierva.',
    ],
    liv: 'Ideal para la noche. Agrégale pollo desmechado para que llene más.',
    adel: 'Dura 4 días en la nevera y se congela bien.',
    con: 'Pollo desmechado o un huevo cocido para la proteína.',
  },
  {
    id: 'pechuga-plancha', o: 'col',
    n: 'Pechuga a la plancha con papa criolla y ensalada', e: '🍗',
    m: ['almuerzo', 'comida'], p: 'pollo', a: ['estufa'], t: 30, d: 'Fácil', kcal: 440, prot: 48,
    ing: [
      [800, 'g', 'pechuga de pollo sin hueso', 'car'],
      [2, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [2, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'orégano seco', 'sal'],
      [500, 'g', 'papa criolla', 'ver'],
      [2, 'taza', 'lechuga picada', 'ver'],
      [2, 'u', 'tomate chonto|tomates chontos', 'ver'],
      [1, 'u', 'pepino cohombro|pepinos cohombros', 'ver'],
      [1, 'u', 'aguacate|aguacates', 'ver'],
      [null, 'gusto', 'sal', 'bas'],
    ],
    pasos: [
      'Abre la pechuga en filetes delgados y adóbala con jugo de limón, ajo machacado, orégano, sal y pimienta. Deja 15 minutos.',
      'Cocina la papa criolla en agua con sal 15 minutos (o en la freidora a 200 °C por 18 minutos).',
      'Pon la sartén bien caliente con poquito aceite y cocina los filetes 4 a 5 minutos por lado, sin moverlos, hasta que doren.',
      'Ensalada: lechuga, tomate, pepino y aguacate con limón y sal.',
    ],
    liv: 'Es de las más livianas: 5 o 6 papitas y ensalada grande.',
    adel: 'Deja la pechuga adobada desde la noche anterior.',
    con: 'Ya es plato completo.',
  },
  {
    id: 'ensalada-atun', o: 'col',
    n: 'Ensalada de atún con aguacate', e: '🐟',
    m: ['almuerzo', 'comida'], p: 'pescado', a: [], t: 15, d: 'Fácil', kcal: 285, prot: 27,
    ing: [
      [3, 'u', 'lata de atún en agua|latas de atún en agua', 'otr'],
      [2, 'u', 'aguacate|aguacates', 'ver'],
      [2, 'u', 'tomate chonto|tomates chontos', 'ver'],
      [0.5, 'u', 'cebolla morada|cebollas moradas', 'ver'],
      [1, 'u', 'pepino cohombro|pepinos cohombros', 'ver'],
      [1, 'taza', 'maíz tierno desgranado', 'otr'],
      [2, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [null, 'gusto', 'cilantro', 'ver'],
      [null, 'gusto', 'sal', 'bas'],
    ],
    pasos: [
      'Escurre bien el atún.',
      'Pica el tomate, la cebolla morada, el pepino y el aguacate en cubitos.',
      'Mezcla todo con el maíz, el jugo de los limones, cilantro picado, sal y pimienta.',
      'Sirve frío.',
    ],
    liv: 'Medio aguacate para todos y sin galletas.',
    adel: 'Pica las verduras en la mañana; el aguacate, al servir.',
    con: 'Galletas integrales, arepa o patacón.',
  },
  {
    id: 'pescado-sudado', o: 'col',
    n: 'Pescado sudado en salsa criolla', e: '🐟',
    m: ['almuerzo', 'comida'], p: 'pescado', a: ['estufa'], t: 30, d: 'Fácil', kcal: 290, prot: 32,
    ing: [
      [800, 'g', 'filete de pescado blanco (basa, tilapia o bagre)', 'car'],
      [3, 'u', 'tomate chonto|tomates chontos', 'ver'],
      [1, 'u', 'cebolla cabezona|cebollas cabezonas', 'ver'],
      [1, 'u', 'pimentón rojo|pimentones rojos', 'ver'],
      [2, 'u', 'diente de ajo|dientes de ajo', 'ver'],
      [1, 'cdta', 'comino', 'bas'],
      [1, 'cdta', 'color (achiote)', 'bas'],
      [0.5, 'taza', 'leche de coco (opcional)', 'otr'],
      [1, 'u', 'limón Tahití|limones Tahití', 'ver'],
      [null, 'gusto', 'cilantro', 'ver'],
      [null, 'gusto', 'sal', 'bas'],
    ],
    pasos: [
      'Corta el pescado en trozos grandes y adóbalo con limón, sal y pimienta.',
      'En una sartén honda sofríe la cebolla, el pimentón, el tomate y el ajo picados con el comino y el color, 8 minutos.',
      'Si quieres, agrega la leche de coco y deja que hierva suave.',
      'Acomoda el pescado encima, tapa y cocina 10 a 12 minutos a fuego bajo, sin revolver para que no se desbarate.',
      'Termina con cilantro.',
    ],
    liv: 'Sin leche de coco, con ensalada y poco arroz.',
    adel: 'Deja el hogao hecho desde el día anterior: así se hace en 15 minutos.',
    con: 'Arroz blanco y patacones.',
  },
  {
    id: 'lomo-cerdo-freidora', o: 'col',
    n: 'Lomo de cerdo en freidora con mostaza y miel', e: '🐖',
    m: ['almuerzo', 'comida'], p: 'cerdo', a: ['freidora|horno'], t: 30, d: 'Fácil', kcal: 320, prot: 42,
    ing: [
      [800, 'g', 'lomo de cerdo en medallones', 'car'],
      [2, 'cdta', 'pimentón en polvo (paprika)', 'sal'],
      [1, 'cdta', 'ajo en polvo', 'bas'],
      [1, 'cdta', 'comino', 'bas'],
      [1, 'cda', 'mostaza (normal)', 'sal'],
      [1, 'cda', 'miel de abejas', 'sal'],
      [null, 'gusto', 'sal', 'bas'],
      [null, 'gusto', 'aceite en spray', 'bas'],
    ],
    pasos: [
      'Mezcla el pimentón, el ajo en polvo, el comino, sal y pimienta, y unta bien los medallones.',
      'Rocía con aceite. Freidora de aire a 200 °C por 12 a 15 minutos, volteando a la mitad (horno: 200 °C por 20 minutos).',
      'Mezcla la mostaza con la miel y pinta el cerdo los últimos 3 minutos.',
      'Antes de servir, corta uno: por dentro debe estar blanco o apenas rosadito, nunca crudo.',
    ],
    liv: 'Con ensalada y verduras; la salsa de mostaza y miel, poquita.',
    adel: 'Deja el cerdo adobado desde la noche anterior.',
    con: 'Puré de papa, ensalada o arroz.',
  },
];
